// Code generated by ent, DO NOT EDIT.

package subscriptionplanversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLTE(FieldID, id))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldPlanID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldVersion, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldPrice, v))
}

// OriginalPrice applies equality check predicate on the "original_price" field. It's identical to OriginalPriceEQ.
func OriginalPrice(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldOriginalPrice, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldCurrency, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityUnit applies equality check predicate on the "validity_unit" field. It's identical to ValidityUnitEQ.
func ValidityUnit(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldValidityUnit, v))
}

// DailyLimitUsd applies equality check predicate on the "daily_limit_usd" field. It's identical to DailyLimitUsdEQ.
func DailyLimitUsd(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// WeeklyLimitUsd applies equality check predicate on the "weekly_limit_usd" field. It's identical to WeeklyLimitUsdEQ.
func WeeklyLimitUsd(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldWeeklyLimitUsd, v))
}

// MonthlyLimitUsd applies equality check predicate on the "monthly_limit_usd" field. It's identical to MonthlyLimitUsdEQ.
func MonthlyLimitUsd(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldMonthlyLimitUsd, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldPublishedAt, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotIn(FieldPlanID, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLTE(FieldVersion, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLTE(FieldPrice, v))
}

// OriginalPriceEQ applies the EQ predicate on the "original_price" field.
func OriginalPriceEQ(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldOriginalPrice, v))
}

// OriginalPriceNEQ applies the NEQ predicate on the "original_price" field.
func OriginalPriceNEQ(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNEQ(FieldOriginalPrice, v))
}

// OriginalPriceIn applies the In predicate on the "original_price" field.
func OriginalPriceIn(vs ...float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIn(FieldOriginalPrice, vs...))
}

// OriginalPriceNotIn applies the NotIn predicate on the "original_price" field.
func OriginalPriceNotIn(vs ...float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotIn(FieldOriginalPrice, vs...))
}

// OriginalPriceGT applies the GT predicate on the "original_price" field.
func OriginalPriceGT(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGT(FieldOriginalPrice, v))
}

// OriginalPriceGTE applies the GTE predicate on the "original_price" field.
func OriginalPriceGTE(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGTE(FieldOriginalPrice, v))
}

// OriginalPriceLT applies the LT predicate on the "original_price" field.
func OriginalPriceLT(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLT(FieldOriginalPrice, v))
}

// OriginalPriceLTE applies the LTE predicate on the "original_price" field.
func OriginalPriceLTE(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLTE(FieldOriginalPrice, v))
}

// OriginalPriceIsNil applies the IsNil predicate on the "original_price" field.
func OriginalPriceIsNil() predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIsNull(FieldOriginalPrice))
}

// OriginalPriceNotNil applies the NotNil predicate on the "original_price" field.
func OriginalPriceNotNil() predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotNull(FieldOriginalPrice))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldContainsFold(FieldCurrency, v))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLTE(FieldValidityDays, v))
}

// ValidityUnitEQ applies the EQ predicate on the "validity_unit" field.
func ValidityUnitEQ(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldValidityUnit, v))
}

// ValidityUnitNEQ applies the NEQ predicate on the "validity_unit" field.
func ValidityUnitNEQ(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNEQ(FieldValidityUnit, v))
}

// ValidityUnitIn applies the In predicate on the "validity_unit" field.
func ValidityUnitIn(vs ...string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIn(FieldValidityUnit, vs...))
}

// ValidityUnitNotIn applies the NotIn predicate on the "validity_unit" field.
func ValidityUnitNotIn(vs ...string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotIn(FieldValidityUnit, vs...))
}

// ValidityUnitGT applies the GT predicate on the "validity_unit" field.
func ValidityUnitGT(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGT(FieldValidityUnit, v))
}

// ValidityUnitGTE applies the GTE predicate on the "validity_unit" field.
func ValidityUnitGTE(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGTE(FieldValidityUnit, v))
}

// ValidityUnitLT applies the LT predicate on the "validity_unit" field.
func ValidityUnitLT(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLT(FieldValidityUnit, v))
}

// ValidityUnitLTE applies the LTE predicate on the "validity_unit" field.
func ValidityUnitLTE(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLTE(FieldValidityUnit, v))
}

// ValidityUnitContains applies the Contains predicate on the "validity_unit" field.
func ValidityUnitContains(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldContains(FieldValidityUnit, v))
}

// ValidityUnitHasPrefix applies the HasPrefix predicate on the "validity_unit" field.
func ValidityUnitHasPrefix(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldHasPrefix(FieldValidityUnit, v))
}

// ValidityUnitHasSuffix applies the HasSuffix predicate on the "validity_unit" field.
func ValidityUnitHasSuffix(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldHasSuffix(FieldValidityUnit, v))
}

// ValidityUnitEqualFold applies the EqualFold predicate on the "validity_unit" field.
func ValidityUnitEqualFold(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEqualFold(FieldValidityUnit, v))
}

// ValidityUnitContainsFold applies the ContainsFold predicate on the "validity_unit" field.
func ValidityUnitContainsFold(v string) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldContainsFold(FieldValidityUnit, v))
}

// DailyLimitUsdEQ applies the EQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdEQ(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdNEQ applies the NEQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdNEQ(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdIn applies the In predicate on the "daily_limit_usd" field.
func DailyLimitUsdIn(vs ...float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdNotIn applies the NotIn predicate on the "daily_limit_usd" field.
func DailyLimitUsdNotIn(vs ...float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdGT applies the GT predicate on the "daily_limit_usd" field.
func DailyLimitUsdGT(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdGTE applies the GTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdGTE(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGTE(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLT applies the LT predicate on the "daily_limit_usd" field.
func DailyLimitUsdLT(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLTE applies the LTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdLTE(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLTE(FieldDailyLimitUsd, v))
}

// DailyLimitUsdIsNil applies the IsNil predicate on the "daily_limit_usd" field.
func DailyLimitUsdIsNil() predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIsNull(FieldDailyLimitUsd))
}

// DailyLimitUsdNotNil applies the NotNil predicate on the "daily_limit_usd" field.
func DailyLimitUsdNotNil() predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotNull(FieldDailyLimitUsd))
}

// WeeklyLimitUsdEQ applies the EQ predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdEQ(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdNEQ applies the NEQ predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNEQ(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNEQ(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdIn applies the In predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdIn(vs ...float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIn(FieldWeeklyLimitUsd, vs...))
}

// WeeklyLimitUsdNotIn applies the NotIn predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNotIn(vs ...float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotIn(FieldWeeklyLimitUsd, vs...))
}

// WeeklyLimitUsdGT applies the GT predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdGT(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGT(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdGTE applies the GTE predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdGTE(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGTE(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdLT applies the LT predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdLT(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLT(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdLTE applies the LTE predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdLTE(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLTE(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdIsNil applies the IsNil predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdIsNil() predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIsNull(FieldWeeklyLimitUsd))
}

// WeeklyLimitUsdNotNil applies the NotNil predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNotNil() predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotNull(FieldWeeklyLimitUsd))
}

// MonthlyLimitUsdEQ applies the EQ predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdEQ(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdNEQ applies the NEQ predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNEQ(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNEQ(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdIn applies the In predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdIn(vs ...float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIn(FieldMonthlyLimitUsd, vs...))
}

// MonthlyLimitUsdNotIn applies the NotIn predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNotIn(vs ...float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotIn(FieldMonthlyLimitUsd, vs...))
}

// MonthlyLimitUsdGT applies the GT predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdGT(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGT(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdGTE applies the GTE predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdGTE(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGTE(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdLT applies the LT predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdLT(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLT(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdLTE applies the LTE predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdLTE(v float64) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLTE(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdIsNil applies the IsNil predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdIsNil() predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIsNull(FieldMonthlyLimitUsd))
}

// MonthlyLimitUsdNotNil applies the NotNil predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNotNil() predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotNull(FieldMonthlyLimitUsd))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.FieldLTE(FieldPublishedAt, v))
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.SubscriptionPlan) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubscriptions applies the HasEdge predicate on the "subscriptions" edge.
func HasSubscriptions() predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubscriptionsTable, SubscriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionsWith applies the HasEdge predicate on the "subscriptions" edge with a given conditions (other predicates).
func HasSubscriptionsWith(preds ...predicate.UserSubscription) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(func(s *sql.Selector) {
		step := newSubscriptionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRedeemCodes applies the HasEdge predicate on the "redeem_codes" edge.
func HasRedeemCodes() predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RedeemCodesTable, RedeemCodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRedeemCodesWith applies the HasEdge predicate on the "redeem_codes" edge with a given conditions (other predicates).
func HasRedeemCodesWith(preds ...predicate.RedeemCode) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(func(s *sql.Selector) {
		step := newRedeemCodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionPlanVersion) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionPlanVersion) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionPlanVersion) predicate.SubscriptionPlanVersion {
	return predicate.SubscriptionPlanVersion(sql.NotPredicates(p))
}
