// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/billingreservation"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BillingReservationDelete is the builder for deleting a BillingReservation entity.
type BillingReservationDelete struct {
	config
	hooks    []Hook
	mutation *BillingReservationMutation
}

// Where appends a list predicates to the BillingReservationDelete builder.
func (_d *BillingReservationDelete) Where(ps ...predicate.BillingReservation) *BillingReservationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BillingReservationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BillingReservationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BillingReservationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(billingreservation.Table, sqlgraph.NewFieldSpec(billingreservation.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BillingReservationDeleteOne is the builder for deleting a single BillingReservation entity.
type BillingReservationDeleteOne struct {
	_d *BillingReservationDelete
}

// Where appends a list predicates to the BillingReservationDelete builder.
func (_d *BillingReservationDeleteOne) Where(ps ...predicate.BillingReservation) *BillingReservationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BillingReservationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{billingreservation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BillingReservationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
