// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/billingreservation"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BillingReservationUpdate is the builder for updating BillingReservation entities.
type BillingReservationUpdate struct {
	config
	hooks    []Hook
	mutation *BillingReservationMutation
}

// Where appends a list predicates to the BillingReservationUpdate builder.
func (_u *BillingReservationUpdate) Where(ps ...predicate.BillingReservation) *BillingReservationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *BillingReservationUpdate) SetRequestID(v string) *BillingReservationUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableRequestID(v *string) *BillingReservationUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *BillingReservationUpdate) SetAPIKeyID(v int64) *BillingReservationUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableAPIKeyID(v *int64) *BillingReservationUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *BillingReservationUpdate) AddAPIKeyID(v int64) *BillingReservationUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BillingReservationUpdate) SetUserID(v int64) *BillingReservationUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableUserID(v *int64) *BillingReservationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *BillingReservationUpdate) AddUserID(v int64) *BillingReservationUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetFundingSource sets the "funding_source" field.
func (_u *BillingReservationUpdate) SetFundingSource(v string) *BillingReservationUpdate {
	_u.mutation.SetFundingSource(v)
	return _u
}

// SetNillableFundingSource sets the "funding_source" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableFundingSource(v *string) *BillingReservationUpdate {
	if v != nil {
		_u.SetFundingSource(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *BillingReservationUpdate) SetSubscriptionID(v int64) *BillingReservationUpdate {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableSubscriptionID(v *int64) *BillingReservationUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *BillingReservationUpdate) AddSubscriptionID(v int64) *BillingReservationUpdate {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *BillingReservationUpdate) ClearSubscriptionID() *BillingReservationUpdate {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetAuthorizedAmount sets the "authorized_amount" field.
func (_u *BillingReservationUpdate) SetAuthorizedAmount(v float64) *BillingReservationUpdate {
	_u.mutation.ResetAuthorizedAmount()
	_u.mutation.SetAuthorizedAmount(v)
	return _u
}

// SetNillableAuthorizedAmount sets the "authorized_amount" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableAuthorizedAmount(v *float64) *BillingReservationUpdate {
	if v != nil {
		_u.SetAuthorizedAmount(*v)
	}
	return _u
}

// AddAuthorizedAmount adds value to the "authorized_amount" field.
func (_u *BillingReservationUpdate) AddAuthorizedAmount(v float64) *BillingReservationUpdate {
	_u.mutation.AddAuthorizedAmount(v)
	return _u
}

// SetCapturedAmount sets the "captured_amount" field.
func (_u *BillingReservationUpdate) SetCapturedAmount(v float64) *BillingReservationUpdate {
	_u.mutation.ResetCapturedAmount()
	_u.mutation.SetCapturedAmount(v)
	return _u
}

// SetNillableCapturedAmount sets the "captured_amount" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableCapturedAmount(v *float64) *BillingReservationUpdate {
	if v != nil {
		_u.SetCapturedAmount(*v)
	}
	return _u
}

// AddCapturedAmount adds value to the "captured_amount" field.
func (_u *BillingReservationUpdate) AddCapturedAmount(v float64) *BillingReservationUpdate {
	_u.mutation.AddCapturedAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *BillingReservationUpdate) SetStatus(v string) *BillingReservationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableStatus(v *string) *BillingReservationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthorizationFingerprint sets the "authorization_fingerprint" field.
func (_u *BillingReservationUpdate) SetAuthorizationFingerprint(v string) *BillingReservationUpdate {
	_u.mutation.SetAuthorizationFingerprint(v)
	return _u
}

// SetNillableAuthorizationFingerprint sets the "authorization_fingerprint" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableAuthorizationFingerprint(v *string) *BillingReservationUpdate {
	if v != nil {
		_u.SetAuthorizationFingerprint(*v)
	}
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *BillingReservationUpdate) SetRequestFingerprint(v string) *BillingReservationUpdate {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableRequestFingerprint(v *string) *BillingReservationUpdate {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *BillingReservationUpdate) SetDailyWindowStart(v time.Time) *BillingReservationUpdate {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableDailyWindowStart(v *time.Time) *BillingReservationUpdate {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (_u *BillingReservationUpdate) ClearDailyWindowStart() *BillingReservationUpdate {
	_u.mutation.ClearDailyWindowStart()
	return _u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_u *BillingReservationUpdate) SetWeeklyWindowStart(v time.Time) *BillingReservationUpdate {
	_u.mutation.SetWeeklyWindowStart(v)
	return _u
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableWeeklyWindowStart(v *time.Time) *BillingReservationUpdate {
	if v != nil {
		_u.SetWeeklyWindowStart(*v)
	}
	return _u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (_u *BillingReservationUpdate) ClearWeeklyWindowStart() *BillingReservationUpdate {
	_u.mutation.ClearWeeklyWindowStart()
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *BillingReservationUpdate) SetMonthlyWindowStart(v time.Time) *BillingReservationUpdate {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableMonthlyWindowStart(v *time.Time) *BillingReservationUpdate {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *BillingReservationUpdate) ClearMonthlyWindowStart() *BillingReservationUpdate {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// SetAsyncTaskID sets the "async_task_id" field.
func (_u *BillingReservationUpdate) SetAsyncTaskID(v string) *BillingReservationUpdate {
	_u.mutation.SetAsyncTaskID(v)
	return _u
}

// SetNillableAsyncTaskID sets the "async_task_id" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableAsyncTaskID(v *string) *BillingReservationUpdate {
	if v != nil {
		_u.SetAsyncTaskID(*v)
	}
	return _u
}

// ClearAsyncTaskID clears the value of the "async_task_id" field.
func (_u *BillingReservationUpdate) ClearAsyncTaskID() *BillingReservationUpdate {
	_u.mutation.ClearAsyncTaskID()
	return _u
}

// SetAsyncMetadata sets the "async_metadata" field.
func (_u *BillingReservationUpdate) SetAsyncMetadata(v json.RawMessage) *BillingReservationUpdate {
	_u.mutation.SetAsyncMetadata(v)
	return _u
}

// AppendAsyncMetadata appends value to the "async_metadata" field.
func (_u *BillingReservationUpdate) AppendAsyncMetadata(v json.RawMessage) *BillingReservationUpdate {
	_u.mutation.AppendAsyncMetadata(v)
	return _u
}

// ClearAsyncMetadata clears the value of the "async_metadata" field.
func (_u *BillingReservationUpdate) ClearAsyncMetadata() *BillingReservationUpdate {
	_u.mutation.ClearAsyncMetadata()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BillingReservationUpdate) SetExpiresAt(v time.Time) *BillingReservationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BillingReservationUpdate) SetNillableExpiresAt(v *time.Time) *BillingReservationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BillingReservationUpdate) SetUpdatedAt(v time.Time) *BillingReservationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BillingReservationMutation object of the builder.
func (_u *BillingReservationUpdate) Mutation() *BillingReservationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BillingReservationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillingReservationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BillingReservationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillingReservationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BillingReservationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := billingreservation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillingReservationUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := billingreservation.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FundingSource(); ok {
		if err := billingreservation.FundingSourceValidator(v); err != nil {
			return &ValidationError{Name: "funding_source", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.funding_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := billingreservation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorizationFingerprint(); ok {
		if err := billingreservation.AuthorizationFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "authorization_fingerprint", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.authorization_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestFingerprint(); ok {
		if err := billingreservation.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.request_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AsyncTaskID(); ok {
		if err := billingreservation.AsyncTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "async_task_id", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.async_task_id": %w`, err)}
		}
	}
	return nil
}

func (_u *BillingReservationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(billingreservation.Table, billingreservation.Columns, sqlgraph.NewFieldSpec(billingreservation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(billingreservation.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(billingreservation.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(billingreservation.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(billingreservation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(billingreservation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FundingSource(); ok {
		_spec.SetField(billingreservation.FieldFundingSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(billingreservation.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(billingreservation.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(billingreservation.FieldSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AuthorizedAmount(); ok {
		_spec.SetField(billingreservation.FieldAuthorizedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAuthorizedAmount(); ok {
		_spec.AddField(billingreservation.FieldAuthorizedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CapturedAmount(); ok {
		_spec.SetField(billingreservation.FieldCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCapturedAmount(); ok {
		_spec.AddField(billingreservation.FieldCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(billingreservation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorizationFingerprint(); ok {
		_spec.SetField(billingreservation.FieldAuthorizationFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(billingreservation.FieldRequestFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(billingreservation.FieldDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.DailyWindowStartCleared() {
		_spec.ClearField(billingreservation.FieldDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(billingreservation.FieldWeeklyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.WeeklyWindowStartCleared() {
		_spec.ClearField(billingreservation.FieldWeeklyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(billingreservation.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(billingreservation.FieldMonthlyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.AsyncTaskID(); ok {
		_spec.SetField(billingreservation.FieldAsyncTaskID, field.TypeString, value)
	}
	if _u.mutation.AsyncTaskIDCleared() {
		_spec.ClearField(billingreservation.FieldAsyncTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.AsyncMetadata(); ok {
		_spec.SetField(billingreservation.FieldAsyncMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAsyncMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, billingreservation.FieldAsyncMetadata, value)
		})
	}
	if _u.mutation.AsyncMetadataCleared() {
		_spec.ClearField(billingreservation.FieldAsyncMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(billingreservation.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(billingreservation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billingreservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BillingReservationUpdateOne is the builder for updating a single BillingReservation entity.
type BillingReservationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BillingReservationMutation
}

// SetRequestID sets the "request_id" field.
func (_u *BillingReservationUpdateOne) SetRequestID(v string) *BillingReservationUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableRequestID(v *string) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *BillingReservationUpdateOne) SetAPIKeyID(v int64) *BillingReservationUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableAPIKeyID(v *int64) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *BillingReservationUpdateOne) AddAPIKeyID(v int64) *BillingReservationUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BillingReservationUpdateOne) SetUserID(v int64) *BillingReservationUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableUserID(v *int64) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *BillingReservationUpdateOne) AddUserID(v int64) *BillingReservationUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetFundingSource sets the "funding_source" field.
func (_u *BillingReservationUpdateOne) SetFundingSource(v string) *BillingReservationUpdateOne {
	_u.mutation.SetFundingSource(v)
	return _u
}

// SetNillableFundingSource sets the "funding_source" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableFundingSource(v *string) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetFundingSource(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *BillingReservationUpdateOne) SetSubscriptionID(v int64) *BillingReservationUpdateOne {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableSubscriptionID(v *int64) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *BillingReservationUpdateOne) AddSubscriptionID(v int64) *BillingReservationUpdateOne {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *BillingReservationUpdateOne) ClearSubscriptionID() *BillingReservationUpdateOne {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetAuthorizedAmount sets the "authorized_amount" field.
func (_u *BillingReservationUpdateOne) SetAuthorizedAmount(v float64) *BillingReservationUpdateOne {
	_u.mutation.ResetAuthorizedAmount()
	_u.mutation.SetAuthorizedAmount(v)
	return _u
}

// SetNillableAuthorizedAmount sets the "authorized_amount" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableAuthorizedAmount(v *float64) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetAuthorizedAmount(*v)
	}
	return _u
}

// AddAuthorizedAmount adds value to the "authorized_amount" field.
func (_u *BillingReservationUpdateOne) AddAuthorizedAmount(v float64) *BillingReservationUpdateOne {
	_u.mutation.AddAuthorizedAmount(v)
	return _u
}

// SetCapturedAmount sets the "captured_amount" field.
func (_u *BillingReservationUpdateOne) SetCapturedAmount(v float64) *BillingReservationUpdateOne {
	_u.mutation.ResetCapturedAmount()
	_u.mutation.SetCapturedAmount(v)
	return _u
}

// SetNillableCapturedAmount sets the "captured_amount" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableCapturedAmount(v *float64) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetCapturedAmount(*v)
	}
	return _u
}

// AddCapturedAmount adds value to the "captured_amount" field.
func (_u *BillingReservationUpdateOne) AddCapturedAmount(v float64) *BillingReservationUpdateOne {
	_u.mutation.AddCapturedAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *BillingReservationUpdateOne) SetStatus(v string) *BillingReservationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableStatus(v *string) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAuthorizationFingerprint sets the "authorization_fingerprint" field.
func (_u *BillingReservationUpdateOne) SetAuthorizationFingerprint(v string) *BillingReservationUpdateOne {
	_u.mutation.SetAuthorizationFingerprint(v)
	return _u
}

// SetNillableAuthorizationFingerprint sets the "authorization_fingerprint" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableAuthorizationFingerprint(v *string) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetAuthorizationFingerprint(*v)
	}
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *BillingReservationUpdateOne) SetRequestFingerprint(v string) *BillingReservationUpdateOne {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableRequestFingerprint(v *string) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *BillingReservationUpdateOne) SetDailyWindowStart(v time.Time) *BillingReservationUpdateOne {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableDailyWindowStart(v *time.Time) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (_u *BillingReservationUpdateOne) ClearDailyWindowStart() *BillingReservationUpdateOne {
	_u.mutation.ClearDailyWindowStart()
	return _u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_u *BillingReservationUpdateOne) SetWeeklyWindowStart(v time.Time) *BillingReservationUpdateOne {
	_u.mutation.SetWeeklyWindowStart(v)
	return _u
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableWeeklyWindowStart(v *time.Time) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetWeeklyWindowStart(*v)
	}
	return _u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (_u *BillingReservationUpdateOne) ClearWeeklyWindowStart() *BillingReservationUpdateOne {
	_u.mutation.ClearWeeklyWindowStart()
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *BillingReservationUpdateOne) SetMonthlyWindowStart(v time.Time) *BillingReservationUpdateOne {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableMonthlyWindowStart(v *time.Time) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *BillingReservationUpdateOne) ClearMonthlyWindowStart() *BillingReservationUpdateOne {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// SetAsyncTaskID sets the "async_task_id" field.
func (_u *BillingReservationUpdateOne) SetAsyncTaskID(v string) *BillingReservationUpdateOne {
	_u.mutation.SetAsyncTaskID(v)
	return _u
}

// SetNillableAsyncTaskID sets the "async_task_id" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableAsyncTaskID(v *string) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetAsyncTaskID(*v)
	}
	return _u
}

// ClearAsyncTaskID clears the value of the "async_task_id" field.
func (_u *BillingReservationUpdateOne) ClearAsyncTaskID() *BillingReservationUpdateOne {
	_u.mutation.ClearAsyncTaskID()
	return _u
}

// SetAsyncMetadata sets the "async_metadata" field.
func (_u *BillingReservationUpdateOne) SetAsyncMetadata(v json.RawMessage) *BillingReservationUpdateOne {
	_u.mutation.SetAsyncMetadata(v)
	return _u
}

// AppendAsyncMetadata appends value to the "async_metadata" field.
func (_u *BillingReservationUpdateOne) AppendAsyncMetadata(v json.RawMessage) *BillingReservationUpdateOne {
	_u.mutation.AppendAsyncMetadata(v)
	return _u
}

// ClearAsyncMetadata clears the value of the "async_metadata" field.
func (_u *BillingReservationUpdateOne) ClearAsyncMetadata() *BillingReservationUpdateOne {
	_u.mutation.ClearAsyncMetadata()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BillingReservationUpdateOne) SetExpiresAt(v time.Time) *BillingReservationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BillingReservationUpdateOne) SetNillableExpiresAt(v *time.Time) *BillingReservationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BillingReservationUpdateOne) SetUpdatedAt(v time.Time) *BillingReservationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BillingReservationMutation object of the builder.
func (_u *BillingReservationUpdateOne) Mutation() *BillingReservationMutation {
	return _u.mutation
}

// Where appends a list predicates to the BillingReservationUpdate builder.
func (_u *BillingReservationUpdateOne) Where(ps ...predicate.BillingReservation) *BillingReservationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BillingReservationUpdateOne) Select(field string, fields ...string) *BillingReservationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BillingReservation entity.
func (_u *BillingReservationUpdateOne) Save(ctx context.Context) (*BillingReservation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillingReservationUpdateOne) SaveX(ctx context.Context) *BillingReservation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BillingReservationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillingReservationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BillingReservationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := billingreservation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillingReservationUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := billingreservation.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FundingSource(); ok {
		if err := billingreservation.FundingSourceValidator(v); err != nil {
			return &ValidationError{Name: "funding_source", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.funding_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := billingreservation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorizationFingerprint(); ok {
		if err := billingreservation.AuthorizationFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "authorization_fingerprint", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.authorization_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestFingerprint(); ok {
		if err := billingreservation.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.request_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AsyncTaskID(); ok {
		if err := billingreservation.AsyncTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "async_task_id", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.async_task_id": %w`, err)}
		}
	}
	return nil
}

func (_u *BillingReservationUpdateOne) sqlSave(ctx context.Context) (_node *BillingReservation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(billingreservation.Table, billingreservation.Columns, sqlgraph.NewFieldSpec(billingreservation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BillingReservation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, billingreservation.FieldID)
		for _, f := range fields {
			if !billingreservation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != billingreservation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(billingreservation.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(billingreservation.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(billingreservation.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(billingreservation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(billingreservation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FundingSource(); ok {
		_spec.SetField(billingreservation.FieldFundingSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(billingreservation.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(billingreservation.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(billingreservation.FieldSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AuthorizedAmount(); ok {
		_spec.SetField(billingreservation.FieldAuthorizedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAuthorizedAmount(); ok {
		_spec.AddField(billingreservation.FieldAuthorizedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CapturedAmount(); ok {
		_spec.SetField(billingreservation.FieldCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCapturedAmount(); ok {
		_spec.AddField(billingreservation.FieldCapturedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(billingreservation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorizationFingerprint(); ok {
		_spec.SetField(billingreservation.FieldAuthorizationFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(billingreservation.FieldRequestFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(billingreservation.FieldDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.DailyWindowStartCleared() {
		_spec.ClearField(billingreservation.FieldDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(billingreservation.FieldWeeklyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.WeeklyWindowStartCleared() {
		_spec.ClearField(billingreservation.FieldWeeklyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(billingreservation.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(billingreservation.FieldMonthlyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.AsyncTaskID(); ok {
		_spec.SetField(billingreservation.FieldAsyncTaskID, field.TypeString, value)
	}
	if _u.mutation.AsyncTaskIDCleared() {
		_spec.ClearField(billingreservation.FieldAsyncTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.AsyncMetadata(); ok {
		_spec.SetField(billingreservation.FieldAsyncMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAsyncMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, billingreservation.FieldAsyncMetadata, value)
		})
	}
	if _u.mutation.AsyncMetadataCleared() {
		_spec.ClearField(billingreservation.FieldAsyncMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(billingreservation.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(billingreservation.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &BillingReservation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billingreservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
