// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/billingreservation"
)

// BillingReservationCreate is the builder for creating a BillingReservation entity.
type BillingReservationCreate struct {
	config
	mutation *BillingReservationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *BillingReservationCreate) SetRequestID(v string) *BillingReservationCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *BillingReservationCreate) SetAPIKeyID(v int64) *BillingReservationCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *BillingReservationCreate) SetUserID(v int64) *BillingReservationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetFundingSource sets the "funding_source" field.
func (_c *BillingReservationCreate) SetFundingSource(v string) *BillingReservationCreate {
	_c.mutation.SetFundingSource(v)
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *BillingReservationCreate) SetSubscriptionID(v int64) *BillingReservationCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_c *BillingReservationCreate) SetNillableSubscriptionID(v *int64) *BillingReservationCreate {
	if v != nil {
		_c.SetSubscriptionID(*v)
	}
	return _c
}

// SetAuthorizedAmount sets the "authorized_amount" field.
func (_c *BillingReservationCreate) SetAuthorizedAmount(v float64) *BillingReservationCreate {
	_c.mutation.SetAuthorizedAmount(v)
	return _c
}

// SetNillableAuthorizedAmount sets the "authorized_amount" field if the given value is not nil.
func (_c *BillingReservationCreate) SetNillableAuthorizedAmount(v *float64) *BillingReservationCreate {
	if v != nil {
		_c.SetAuthorizedAmount(*v)
	}
	return _c
}

// SetCapturedAmount sets the "captured_amount" field.
func (_c *BillingReservationCreate) SetCapturedAmount(v float64) *BillingReservationCreate {
	_c.mutation.SetCapturedAmount(v)
	return _c
}

// SetNillableCapturedAmount sets the "captured_amount" field if the given value is not nil.
func (_c *BillingReservationCreate) SetNillableCapturedAmount(v *float64) *BillingReservationCreate {
	if v != nil {
		_c.SetCapturedAmount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BillingReservationCreate) SetStatus(v string) *BillingReservationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BillingReservationCreate) SetNillableStatus(v *string) *BillingReservationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAuthorizationFingerprint sets the "authorization_fingerprint" field.
func (_c *BillingReservationCreate) SetAuthorizationFingerprint(v string) *BillingReservationCreate {
	_c.mutation.SetAuthorizationFingerprint(v)
	return _c
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_c *BillingReservationCreate) SetRequestFingerprint(v string) *BillingReservationCreate {
	_c.mutation.SetRequestFingerprint(v)
	return _c
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_c *BillingReservationCreate) SetNillableRequestFingerprint(v *string) *BillingReservationCreate {
	if v != nil {
		_c.SetRequestFingerprint(*v)
	}
	return _c
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_c *BillingReservationCreate) SetDailyWindowStart(v time.Time) *BillingReservationCreate {
	_c.mutation.SetDailyWindowStart(v)
	return _c
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_c *BillingReservationCreate) SetNillableDailyWindowStart(v *time.Time) *BillingReservationCreate {
	if v != nil {
		_c.SetDailyWindowStart(*v)
	}
	return _c
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_c *BillingReservationCreate) SetWeeklyWindowStart(v time.Time) *BillingReservationCreate {
	_c.mutation.SetWeeklyWindowStart(v)
	return _c
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_c *BillingReservationCreate) SetNillableWeeklyWindowStart(v *time.Time) *BillingReservationCreate {
	if v != nil {
		_c.SetWeeklyWindowStart(*v)
	}
	return _c
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_c *BillingReservationCreate) SetMonthlyWindowStart(v time.Time) *BillingReservationCreate {
	_c.mutation.SetMonthlyWindowStart(v)
	return _c
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_c *BillingReservationCreate) SetNillableMonthlyWindowStart(v *time.Time) *BillingReservationCreate {
	if v != nil {
		_c.SetMonthlyWindowStart(*v)
	}
	return _c
}

// SetAsyncTaskID sets the "async_task_id" field.
func (_c *BillingReservationCreate) SetAsyncTaskID(v string) *BillingReservationCreate {
	_c.mutation.SetAsyncTaskID(v)
	return _c
}

// SetNillableAsyncTaskID sets the "async_task_id" field if the given value is not nil.
func (_c *BillingReservationCreate) SetNillableAsyncTaskID(v *string) *BillingReservationCreate {
	if v != nil {
		_c.SetAsyncTaskID(*v)
	}
	return _c
}

// SetAsyncMetadata sets the "async_metadata" field.
func (_c *BillingReservationCreate) SetAsyncMetadata(v json.RawMessage) *BillingReservationCreate {
	_c.mutation.SetAsyncMetadata(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *BillingReservationCreate) SetExpiresAt(v time.Time) *BillingReservationCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BillingReservationCreate) SetCreatedAt(v time.Time) *BillingReservationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BillingReservationCreate) SetNillableCreatedAt(v *time.Time) *BillingReservationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BillingReservationCreate) SetUpdatedAt(v time.Time) *BillingReservationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BillingReservationCreate) SetNillableUpdatedAt(v *time.Time) *BillingReservationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the BillingReservationMutation object of the builder.
func (_c *BillingReservationCreate) Mutation() *BillingReservationMutation {
	return _c.mutation
}

// Save creates the BillingReservation in the database.
func (_c *BillingReservationCreate) Save(ctx context.Context) (*BillingReservation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BillingReservationCreate) SaveX(ctx context.Context) *BillingReservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingReservationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingReservationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BillingReservationCreate) defaults() {
	if _, ok := _c.mutation.AuthorizedAmount(); !ok {
		v := billingreservation.DefaultAuthorizedAmount
		_c.mutation.SetAuthorizedAmount(v)
	}
	if _, ok := _c.mutation.CapturedAmount(); !ok {
		v := billingreservation.DefaultCapturedAmount
		_c.mutation.SetCapturedAmount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := billingreservation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RequestFingerprint(); !ok {
		v := billingreservation.DefaultRequestFingerprint
		_c.mutation.SetRequestFingerprint(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := billingreservation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := billingreservation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BillingReservationCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "BillingReservation.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := billingreservation.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "BillingReservation.api_key_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "BillingReservation.user_id"`)}
	}
	if _, ok := _c.mutation.FundingSource(); !ok {
		return &ValidationError{Name: "funding_source", err: errors.New(`ent: missing required field "BillingReservation.funding_source"`)}
	}
	if v, ok := _c.mutation.FundingSource(); ok {
		if err := billingreservation.FundingSourceValidator(v); err != nil {
			return &ValidationError{Name: "funding_source", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.funding_source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthorizedAmount(); !ok {
		return &ValidationError{Name: "authorized_amount", err: errors.New(`ent: missing required field "BillingReservation.authorized_amount"`)}
	}
	if _, ok := _c.mutation.CapturedAmount(); !ok {
		return &ValidationError{Name: "captured_amount", err: errors.New(`ent: missing required field "BillingReservation.captured_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BillingReservation.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := billingreservation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthorizationFingerprint(); !ok {
		return &ValidationError{Name: "authorization_fingerprint", err: errors.New(`ent: missing required field "BillingReservation.authorization_fingerprint"`)}
	}
	if v, ok := _c.mutation.AuthorizationFingerprint(); ok {
		if err := billingreservation.AuthorizationFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "authorization_fingerprint", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.authorization_fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestFingerprint(); !ok {
		return &ValidationError{Name: "request_fingerprint", err: errors.New(`ent: missing required field "BillingReservation.request_fingerprint"`)}
	}
	if v, ok := _c.mutation.RequestFingerprint(); ok {
		if err := billingreservation.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.request_fingerprint": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AsyncTaskID(); ok {
		if err := billingreservation.AsyncTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "async_task_id", err: fmt.Errorf(`ent: validator failed for field "BillingReservation.async_task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "BillingReservation.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BillingReservation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BillingReservation.updated_at"`)}
	}
	return nil
}

func (_c *BillingReservationCreate) sqlSave(ctx context.Context) (*BillingReservation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BillingReservationCreate) createSpec() (*BillingReservation, *sqlgraph.CreateSpec) {
	var (
		_node = &BillingReservation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(billingreservation.Table, sqlgraph.NewFieldSpec(billingreservation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(billingreservation.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(billingreservation.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(billingreservation.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.FundingSource(); ok {
		_spec.SetField(billingreservation.FieldFundingSource, field.TypeString, value)
		_node.FundingSource = value
	}
	if value, ok := _c.mutation.SubscriptionID(); ok {
		_spec.SetField(billingreservation.FieldSubscriptionID, field.TypeInt64, value)
		_node.SubscriptionID = &value
	}
	if value, ok := _c.mutation.AuthorizedAmount(); ok {
		_spec.SetField(billingreservation.FieldAuthorizedAmount, field.TypeFloat64, value)
		_node.AuthorizedAmount = value
	}
	if value, ok := _c.mutation.CapturedAmount(); ok {
		_spec.SetField(billingreservation.FieldCapturedAmount, field.TypeFloat64, value)
		_node.CapturedAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(billingreservation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AuthorizationFingerprint(); ok {
		_spec.SetField(billingreservation.FieldAuthorizationFingerprint, field.TypeString, value)
		_node.AuthorizationFingerprint = value
	}
	if value, ok := _c.mutation.RequestFingerprint(); ok {
		_spec.SetField(billingreservation.FieldRequestFingerprint, field.TypeString, value)
		_node.RequestFingerprint = value
	}
	if value, ok := _c.mutation.DailyWindowStart(); ok {
		_spec.SetField(billingreservation.FieldDailyWindowStart, field.TypeTime, value)
		_node.DailyWindowStart = &value
	}
	if value, ok := _c.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(billingreservation.FieldWeeklyWindowStart, field.TypeTime, value)
		_node.WeeklyWindowStart = &value
	}
	if value, ok := _c.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(billingreservation.FieldMonthlyWindowStart, field.TypeTime, value)
		_node.MonthlyWindowStart = &value
	}
	if value, ok := _c.mutation.AsyncTaskID(); ok {
		_spec.SetField(billingreservation.FieldAsyncTaskID, field.TypeString, value)
		_node.AsyncTaskID = &value
	}
	if value, ok := _c.mutation.AsyncMetadata(); ok {
		_spec.SetField(billingreservation.FieldAsyncMetadata, field.TypeJSON, value)
		_node.AsyncMetadata = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(billingreservation.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(billingreservation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(billingreservation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BillingReservation.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BillingReservationUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *BillingReservationCreate) OnConflict(opts ...sql.ConflictOption) *BillingReservationUpsertOne {
	_c.conflict = opts
	return &BillingReservationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BillingReservation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BillingReservationCreate) OnConflictColumns(columns ...string) *BillingReservationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BillingReservationUpsertOne{
		create: _c,
	}
}

type (
	// BillingReservationUpsertOne is the builder for "upsert"-ing
	//  one BillingReservation node.
	BillingReservationUpsertOne struct {
		create *BillingReservationCreate
	}

	// BillingReservationUpsert is the "OnConflict" setter.
	BillingReservationUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *BillingReservationUpsert) SetRequestID(v string) *BillingReservationUpsert {
	u.Set(billingreservation.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateRequestID() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldRequestID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *BillingReservationUpsert) SetAPIKeyID(v int64) *BillingReservationUpsert {
	u.Set(billingreservation.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateAPIKeyID() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *BillingReservationUpsert) AddAPIKeyID(v int64) *BillingReservationUpsert {
	u.Add(billingreservation.FieldAPIKeyID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *BillingReservationUpsert) SetUserID(v int64) *BillingReservationUpsert {
	u.Set(billingreservation.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateUserID() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *BillingReservationUpsert) AddUserID(v int64) *BillingReservationUpsert {
	u.Add(billingreservation.FieldUserID, v)
	return u
}

// SetFundingSource sets the "funding_source" field.
func (u *BillingReservationUpsert) SetFundingSource(v string) *BillingReservationUpsert {
	u.Set(billingreservation.FieldFundingSource, v)
	return u
}

// UpdateFundingSource sets the "funding_source" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateFundingSource() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldFundingSource)
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *BillingReservationUpsert) SetSubscriptionID(v int64) *BillingReservationUpsert {
	u.Set(billingreservation.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateSubscriptionID() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldSubscriptionID)
	return u
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *BillingReservationUpsert) AddSubscriptionID(v int64) *BillingReservationUpsert {
	u.Add(billingreservation.FieldSubscriptionID, v)
	return u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *BillingReservationUpsert) ClearSubscriptionID() *BillingReservationUpsert {
	u.SetNull(billingreservation.FieldSubscriptionID)
	return u
}

// SetAuthorizedAmount sets the "authorized_amount" field.
func (u *BillingReservationUpsert) SetAuthorizedAmount(v float64) *BillingReservationUpsert {
	u.Set(billingreservation.FieldAuthorizedAmount, v)
	return u
}

// UpdateAuthorizedAmount sets the "authorized_amount" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateAuthorizedAmount() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldAuthorizedAmount)
	return u
}

// AddAuthorizedAmount adds v to the "authorized_amount" field.
func (u *BillingReservationUpsert) AddAuthorizedAmount(v float64) *BillingReservationUpsert {
	u.Add(billingreservation.FieldAuthorizedAmount, v)
	return u
}

// SetCapturedAmount sets the "captured_amount" field.
func (u *BillingReservationUpsert) SetCapturedAmount(v float64) *BillingReservationUpsert {
	u.Set(billingreservation.FieldCapturedAmount, v)
	return u
}

// UpdateCapturedAmount sets the "captured_amount" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateCapturedAmount() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldCapturedAmount)
	return u
}

// AddCapturedAmount adds v to the "captured_amount" field.
func (u *BillingReservationUpsert) AddCapturedAmount(v float64) *BillingReservationUpsert {
	u.Add(billingreservation.FieldCapturedAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *BillingReservationUpsert) SetStatus(v string) *BillingReservationUpsert {
	u.Set(billingreservation.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateStatus() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldStatus)
	return u
}

// SetAuthorizationFingerprint sets the "authorization_fingerprint" field.
func (u *BillingReservationUpsert) SetAuthorizationFingerprint(v string) *BillingReservationUpsert {
	u.Set(billingreservation.FieldAuthorizationFingerprint, v)
	return u
}

// UpdateAuthorizationFingerprint sets the "authorization_fingerprint" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateAuthorizationFingerprint() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldAuthorizationFingerprint)
	return u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *BillingReservationUpsert) SetRequestFingerprint(v string) *BillingReservationUpsert {
	u.Set(billingreservation.FieldRequestFingerprint, v)
	return u
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateRequestFingerprint() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldRequestFingerprint)
	return u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *BillingReservationUpsert) SetDailyWindowStart(v time.Time) *BillingReservationUpsert {
	u.Set(billingreservation.FieldDailyWindowStart, v)
	return u
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateDailyWindowStart() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldDailyWindowStart)
	return u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *BillingReservationUpsert) ClearDailyWindowStart() *BillingReservationUpsert {
	u.SetNull(billingreservation.FieldDailyWindowStart)
	return u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *BillingReservationUpsert) SetWeeklyWindowStart(v time.Time) *BillingReservationUpsert {
	u.Set(billingreservation.FieldWeeklyWindowStart, v)
	return u
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateWeeklyWindowStart() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldWeeklyWindowStart)
	return u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *BillingReservationUpsert) ClearWeeklyWindowStart() *BillingReservationUpsert {
	u.SetNull(billingreservation.FieldWeeklyWindowStart)
	return u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *BillingReservationUpsert) SetMonthlyWindowStart(v time.Time) *BillingReservationUpsert {
	u.Set(billingreservation.FieldMonthlyWindowStart, v)
	return u
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateMonthlyWindowStart() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldMonthlyWindowStart)
	return u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *BillingReservationUpsert) ClearMonthlyWindowStart() *BillingReservationUpsert {
	u.SetNull(billingreservation.FieldMonthlyWindowStart)
	return u
}

// SetAsyncTaskID sets the "async_task_id" field.
func (u *BillingReservationUpsert) SetAsyncTaskID(v string) *BillingReservationUpsert {
	u.Set(billingreservation.FieldAsyncTaskID, v)
	return u
}

// UpdateAsyncTaskID sets the "async_task_id" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateAsyncTaskID() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldAsyncTaskID)
	return u
}

// ClearAsyncTaskID clears the value of the "async_task_id" field.
func (u *BillingReservationUpsert) ClearAsyncTaskID() *BillingReservationUpsert {
	u.SetNull(billingreservation.FieldAsyncTaskID)
	return u
}

// SetAsyncMetadata sets the "async_metadata" field.
func (u *BillingReservationUpsert) SetAsyncMetadata(v json.RawMessage) *BillingReservationUpsert {
	u.Set(billingreservation.FieldAsyncMetadata, v)
	return u
}

// UpdateAsyncMetadata sets the "async_metadata" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateAsyncMetadata() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldAsyncMetadata)
	return u
}

// ClearAsyncMetadata clears the value of the "async_metadata" field.
func (u *BillingReservationUpsert) ClearAsyncMetadata() *BillingReservationUpsert {
	u.SetNull(billingreservation.FieldAsyncMetadata)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *BillingReservationUpsert) SetExpiresAt(v time.Time) *BillingReservationUpsert {
	u.Set(billingreservation.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateExpiresAt() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldExpiresAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingReservationUpsert) SetUpdatedAt(v time.Time) *BillingReservationUpsert {
	u.Set(billingreservation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingReservationUpsert) UpdateUpdatedAt() *BillingReservationUpsert {
	u.SetExcluded(billingreservation.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BillingReservation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BillingReservationUpsertOne) UpdateNewValues() *BillingReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(billingreservation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BillingReservation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BillingReservationUpsertOne) Ignore() *BillingReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BillingReservationUpsertOne) DoNothing() *BillingReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BillingReservationCreate.OnConflict
// documentation for more info.
func (u *BillingReservationUpsertOne) Update(set func(*BillingReservationUpsert)) *BillingReservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BillingReservationUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *BillingReservationUpsertOne) SetRequestID(v string) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateRequestID() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateRequestID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *BillingReservationUpsertOne) SetAPIKeyID(v int64) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *BillingReservationUpsertOne) AddAPIKeyID(v int64) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateAPIKeyID() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetUserID sets the "user_id" field.
func (u *BillingReservationUpsertOne) SetUserID(v int64) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *BillingReservationUpsertOne) AddUserID(v int64) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateUserID() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateUserID()
	})
}

// SetFundingSource sets the "funding_source" field.
func (u *BillingReservationUpsertOne) SetFundingSource(v string) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetFundingSource(v)
	})
}

// UpdateFundingSource sets the "funding_source" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateFundingSource() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateFundingSource()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *BillingReservationUpsertOne) SetSubscriptionID(v int64) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *BillingReservationUpsertOne) AddSubscriptionID(v int64) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateSubscriptionID() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *BillingReservationUpsertOne) ClearSubscriptionID() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.ClearSubscriptionID()
	})
}

// SetAuthorizedAmount sets the "authorized_amount" field.
func (u *BillingReservationUpsertOne) SetAuthorizedAmount(v float64) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetAuthorizedAmount(v)
	})
}

// AddAuthorizedAmount adds v to the "authorized_amount" field.
func (u *BillingReservationUpsertOne) AddAuthorizedAmount(v float64) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.AddAuthorizedAmount(v)
	})
}

// UpdateAuthorizedAmount sets the "authorized_amount" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateAuthorizedAmount() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateAuthorizedAmount()
	})
}

// SetCapturedAmount sets the "captured_amount" field.
func (u *BillingReservationUpsertOne) SetCapturedAmount(v float64) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetCapturedAmount(v)
	})
}

// AddCapturedAmount adds v to the "captured_amount" field.
func (u *BillingReservationUpsertOne) AddCapturedAmount(v float64) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.AddCapturedAmount(v)
	})
}

// UpdateCapturedAmount sets the "captured_amount" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateCapturedAmount() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateCapturedAmount()
	})
}

// SetStatus sets the "status" field.
func (u *BillingReservationUpsertOne) SetStatus(v string) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateStatus() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateStatus()
	})
}

// SetAuthorizationFingerprint sets the "authorization_fingerprint" field.
func (u *BillingReservationUpsertOne) SetAuthorizationFingerprint(v string) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetAuthorizationFingerprint(v)
	})
}

// UpdateAuthorizationFingerprint sets the "authorization_fingerprint" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateAuthorizationFingerprint() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateAuthorizationFingerprint()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *BillingReservationUpsertOne) SetRequestFingerprint(v string) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateRequestFingerprint() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *BillingReservationUpsertOne) SetDailyWindowStart(v time.Time) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateDailyWindowStart() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *BillingReservationUpsertOne) ClearDailyWindowStart() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *BillingReservationUpsertOne) SetWeeklyWindowStart(v time.Time) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateWeeklyWindowStart() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *BillingReservationUpsertOne) ClearWeeklyWindowStart() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *BillingReservationUpsertOne) SetMonthlyWindowStart(v time.Time) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateMonthlyWindowStart() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *BillingReservationUpsertOne) ClearMonthlyWindowStart() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetAsyncTaskID sets the "async_task_id" field.
func (u *BillingReservationUpsertOne) SetAsyncTaskID(v string) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetAsyncTaskID(v)
	})
}

// UpdateAsyncTaskID sets the "async_task_id" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateAsyncTaskID() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateAsyncTaskID()
	})
}

// ClearAsyncTaskID clears the value of the "async_task_id" field.
func (u *BillingReservationUpsertOne) ClearAsyncTaskID() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.ClearAsyncTaskID()
	})
}

// SetAsyncMetadata sets the "async_metadata" field.
func (u *BillingReservationUpsertOne) SetAsyncMetadata(v json.RawMessage) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetAsyncMetadata(v)
	})
}

// UpdateAsyncMetadata sets the "async_metadata" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateAsyncMetadata() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateAsyncMetadata()
	})
}

// ClearAsyncMetadata clears the value of the "async_metadata" field.
func (u *BillingReservationUpsertOne) ClearAsyncMetadata() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.ClearAsyncMetadata()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *BillingReservationUpsertOne) SetExpiresAt(v time.Time) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateExpiresAt() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingReservationUpsertOne) SetUpdatedAt(v time.Time) *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingReservationUpsertOne) UpdateUpdatedAt() *BillingReservationUpsertOne {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BillingReservationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BillingReservationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BillingReservationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BillingReservationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BillingReservationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BillingReservationCreateBulk is the builder for creating many BillingReservation entities in bulk.
type BillingReservationCreateBulk struct {
	config
	err      error
	builders []*BillingReservationCreate
	conflict []sql.ConflictOption
}

// Save creates the BillingReservation entities in the database.
func (_c *BillingReservationCreateBulk) Save(ctx context.Context) ([]*BillingReservation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BillingReservation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BillingReservationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BillingReservationCreateBulk) SaveX(ctx context.Context) []*BillingReservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingReservationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingReservationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BillingReservation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BillingReservationUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *BillingReservationCreateBulk) OnConflict(opts ...sql.ConflictOption) *BillingReservationUpsertBulk {
	_c.conflict = opts
	return &BillingReservationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BillingReservation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BillingReservationCreateBulk) OnConflictColumns(columns ...string) *BillingReservationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BillingReservationUpsertBulk{
		create: _c,
	}
}

// BillingReservationUpsertBulk is the builder for "upsert"-ing
// a bulk of BillingReservation nodes.
type BillingReservationUpsertBulk struct {
	create *BillingReservationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BillingReservation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BillingReservationUpsertBulk) UpdateNewValues() *BillingReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(billingreservation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BillingReservation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BillingReservationUpsertBulk) Ignore() *BillingReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BillingReservationUpsertBulk) DoNothing() *BillingReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BillingReservationCreateBulk.OnConflict
// documentation for more info.
func (u *BillingReservationUpsertBulk) Update(set func(*BillingReservationUpsert)) *BillingReservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BillingReservationUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *BillingReservationUpsertBulk) SetRequestID(v string) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateRequestID() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateRequestID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *BillingReservationUpsertBulk) SetAPIKeyID(v int64) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *BillingReservationUpsertBulk) AddAPIKeyID(v int64) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateAPIKeyID() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetUserID sets the "user_id" field.
func (u *BillingReservationUpsertBulk) SetUserID(v int64) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *BillingReservationUpsertBulk) AddUserID(v int64) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateUserID() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateUserID()
	})
}

// SetFundingSource sets the "funding_source" field.
func (u *BillingReservationUpsertBulk) SetFundingSource(v string) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetFundingSource(v)
	})
}

// UpdateFundingSource sets the "funding_source" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateFundingSource() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateFundingSource()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *BillingReservationUpsertBulk) SetSubscriptionID(v int64) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *BillingReservationUpsertBulk) AddSubscriptionID(v int64) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateSubscriptionID() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateSubscriptionID()
	})
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (u *BillingReservationUpsertBulk) ClearSubscriptionID() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.ClearSubscriptionID()
	})
}

// SetAuthorizedAmount sets the "authorized_amount" field.
func (u *BillingReservationUpsertBulk) SetAuthorizedAmount(v float64) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetAuthorizedAmount(v)
	})
}

// AddAuthorizedAmount adds v to the "authorized_amount" field.
func (u *BillingReservationUpsertBulk) AddAuthorizedAmount(v float64) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.AddAuthorizedAmount(v)
	})
}

// UpdateAuthorizedAmount sets the "authorized_amount" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateAuthorizedAmount() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateAuthorizedAmount()
	})
}

// SetCapturedAmount sets the "captured_amount" field.
func (u *BillingReservationUpsertBulk) SetCapturedAmount(v float64) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetCapturedAmount(v)
	})
}

// AddCapturedAmount adds v to the "captured_amount" field.
func (u *BillingReservationUpsertBulk) AddCapturedAmount(v float64) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.AddCapturedAmount(v)
	})
}

// UpdateCapturedAmount sets the "captured_amount" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateCapturedAmount() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateCapturedAmount()
	})
}

// SetStatus sets the "status" field.
func (u *BillingReservationUpsertBulk) SetStatus(v string) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateStatus() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateStatus()
	})
}

// SetAuthorizationFingerprint sets the "authorization_fingerprint" field.
func (u *BillingReservationUpsertBulk) SetAuthorizationFingerprint(v string) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetAuthorizationFingerprint(v)
	})
}

// UpdateAuthorizationFingerprint sets the "authorization_fingerprint" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateAuthorizationFingerprint() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateAuthorizationFingerprint()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *BillingReservationUpsertBulk) SetRequestFingerprint(v string) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateRequestFingerprint() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *BillingReservationUpsertBulk) SetDailyWindowStart(v time.Time) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateDailyWindowStart() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *BillingReservationUpsertBulk) ClearDailyWindowStart() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *BillingReservationUpsertBulk) SetWeeklyWindowStart(v time.Time) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateWeeklyWindowStart() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *BillingReservationUpsertBulk) ClearWeeklyWindowStart() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *BillingReservationUpsertBulk) SetMonthlyWindowStart(v time.Time) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateMonthlyWindowStart() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *BillingReservationUpsertBulk) ClearMonthlyWindowStart() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetAsyncTaskID sets the "async_task_id" field.
func (u *BillingReservationUpsertBulk) SetAsyncTaskID(v string) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetAsyncTaskID(v)
	})
}

// UpdateAsyncTaskID sets the "async_task_id" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateAsyncTaskID() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateAsyncTaskID()
	})
}

// ClearAsyncTaskID clears the value of the "async_task_id" field.
func (u *BillingReservationUpsertBulk) ClearAsyncTaskID() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.ClearAsyncTaskID()
	})
}

// SetAsyncMetadata sets the "async_metadata" field.
func (u *BillingReservationUpsertBulk) SetAsyncMetadata(v json.RawMessage) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetAsyncMetadata(v)
	})
}

// UpdateAsyncMetadata sets the "async_metadata" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateAsyncMetadata() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateAsyncMetadata()
	})
}

// ClearAsyncMetadata clears the value of the "async_metadata" field.
func (u *BillingReservationUpsertBulk) ClearAsyncMetadata() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.ClearAsyncMetadata()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *BillingReservationUpsertBulk) SetExpiresAt(v time.Time) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateExpiresAt() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingReservationUpsertBulk) SetUpdatedAt(v time.Time) *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingReservationUpsertBulk) UpdateUpdatedAt() *BillingReservationUpsertBulk {
	return u.Update(func(s *BillingReservationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BillingReservationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BillingReservationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BillingReservationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BillingReservationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
