// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplanversion"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionPlanVersionUpdate is the builder for updating SubscriptionPlanVersion entities.
type SubscriptionPlanVersionUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionPlanVersionMutation
}

// Where appends a list predicates to the SubscriptionPlanVersionUpdate builder.
func (_u *SubscriptionPlanVersionUpdate) Where(ps ...predicate.SubscriptionPlanVersion) *SubscriptionPlanVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *SubscriptionPlanVersionUpdate) SetPlanID(v int64) *SubscriptionPlanVersionUpdate {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdate) SetNillablePlanID(v *int64) *SubscriptionPlanVersionUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *SubscriptionPlanVersionUpdate) SetVersion(v int) *SubscriptionPlanVersionUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdate) SetNillableVersion(v *int) *SubscriptionPlanVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SubscriptionPlanVersionUpdate) AddVersion(v int) *SubscriptionPlanVersionUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *SubscriptionPlanVersionUpdate) SetPrice(v float64) *SubscriptionPlanVersionUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdate) SetNillablePrice(v *float64) *SubscriptionPlanVersionUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *SubscriptionPlanVersionUpdate) AddPrice(v float64) *SubscriptionPlanVersionUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *SubscriptionPlanVersionUpdate) SetOriginalPrice(v float64) *SubscriptionPlanVersionUpdate {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdate) SetNillableOriginalPrice(v *float64) *SubscriptionPlanVersionUpdate {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *SubscriptionPlanVersionUpdate) AddOriginalPrice(v float64) *SubscriptionPlanVersionUpdate {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (_u *SubscriptionPlanVersionUpdate) ClearOriginalPrice() *SubscriptionPlanVersionUpdate {
	_u.mutation.ClearOriginalPrice()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *SubscriptionPlanVersionUpdate) SetCurrency(v string) *SubscriptionPlanVersionUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdate) SetNillableCurrency(v *string) *SubscriptionPlanVersionUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *SubscriptionPlanVersionUpdate) SetValidityDays(v int) *SubscriptionPlanVersionUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdate) SetNillableValidityDays(v *int) *SubscriptionPlanVersionUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *SubscriptionPlanVersionUpdate) AddValidityDays(v int) *SubscriptionPlanVersionUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetValidityUnit sets the "validity_unit" field.
func (_u *SubscriptionPlanVersionUpdate) SetValidityUnit(v string) *SubscriptionPlanVersionUpdate {
	_u.mutation.SetValidityUnit(v)
	return _u
}

// SetNillableValidityUnit sets the "validity_unit" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdate) SetNillableValidityUnit(v *string) *SubscriptionPlanVersionUpdate {
	if v != nil {
		_u.SetValidityUnit(*v)
	}
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdate) SetDailyLimitUsd(v float64) *SubscriptionPlanVersionUpdate {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdate) SetNillableDailyLimitUsd(v *float64) *SubscriptionPlanVersionUpdate {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdate) AddDailyLimitUsd(v float64) *SubscriptionPlanVersionUpdate {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdate) ClearDailyLimitUsd() *SubscriptionPlanVersionUpdate {
	_u.mutation.ClearDailyLimitUsd()
	return _u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdate) SetWeeklyLimitUsd(v float64) *SubscriptionPlanVersionUpdate {
	_u.mutation.ResetWeeklyLimitUsd()
	_u.mutation.SetWeeklyLimitUsd(v)
	return _u
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdate) SetNillableWeeklyLimitUsd(v *float64) *SubscriptionPlanVersionUpdate {
	if v != nil {
		_u.SetWeeklyLimitUsd(*v)
	}
	return _u
}

// AddWeeklyLimitUsd adds value to the "weekly_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdate) AddWeeklyLimitUsd(v float64) *SubscriptionPlanVersionUpdate {
	_u.mutation.AddWeeklyLimitUsd(v)
	return _u
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdate) ClearWeeklyLimitUsd() *SubscriptionPlanVersionUpdate {
	_u.mutation.ClearWeeklyLimitUsd()
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdate) SetMonthlyLimitUsd(v float64) *SubscriptionPlanVersionUpdate {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdate) SetNillableMonthlyLimitUsd(v *float64) *SubscriptionPlanVersionUpdate {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdate) AddMonthlyLimitUsd(v float64) *SubscriptionPlanVersionUpdate {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdate) ClearMonthlyLimitUsd() *SubscriptionPlanVersionUpdate {
	_u.mutation.ClearMonthlyLimitUsd()
	return _u
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_u *SubscriptionPlanVersionUpdate) SetPlan(v *SubscriptionPlan) *SubscriptionPlanVersionUpdate {
	return _u.SetPlanID(v.ID)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (_u *SubscriptionPlanVersionUpdate) AddSubscriptionIDs(ids ...int64) *SubscriptionPlanVersionUpdate {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (_u *SubscriptionPlanVersionUpdate) AddSubscriptions(v ...*UserSubscription) *SubscriptionPlanVersionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_u *SubscriptionPlanVersionUpdate) AddRedeemCodeIDs(ids ...int64) *SubscriptionPlanVersionUpdate {
	_u.mutation.AddRedeemCodeIDs(ids...)
	return _u
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_u *SubscriptionPlanVersionUpdate) AddRedeemCodes(v ...*RedeemCode) *SubscriptionPlanVersionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedeemCodeIDs(ids...)
}

// Mutation returns the SubscriptionPlanVersionMutation object of the builder.
func (_u *SubscriptionPlanVersionUpdate) Mutation() *SubscriptionPlanVersionMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the SubscriptionPlan entity.
func (_u *SubscriptionPlanVersionUpdate) ClearPlan() *SubscriptionPlanVersionUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// ClearSubscriptions clears all "subscriptions" edges to the UserSubscription entity.
func (_u *SubscriptionPlanVersionUpdate) ClearSubscriptions() *SubscriptionPlanVersionUpdate {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to UserSubscription entities by IDs.
func (_u *SubscriptionPlanVersionUpdate) RemoveSubscriptionIDs(ids ...int64) *SubscriptionPlanVersionUpdate {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to UserSubscription entities.
func (_u *SubscriptionPlanVersionUpdate) RemoveSubscriptions(v ...*UserSubscription) *SubscriptionPlanVersionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearRedeemCodes clears all "redeem_codes" edges to the RedeemCode entity.
func (_u *SubscriptionPlanVersionUpdate) ClearRedeemCodes() *SubscriptionPlanVersionUpdate {
	_u.mutation.ClearRedeemCodes()
	return _u
}

// RemoveRedeemCodeIDs removes the "redeem_codes" edge to RedeemCode entities by IDs.
func (_u *SubscriptionPlanVersionUpdate) RemoveRedeemCodeIDs(ids ...int64) *SubscriptionPlanVersionUpdate {
	_u.mutation.RemoveRedeemCodeIDs(ids...)
	return _u
}

// RemoveRedeemCodes removes "redeem_codes" edges to RedeemCode entities.
func (_u *SubscriptionPlanVersionUpdate) RemoveRedeemCodes(v ...*RedeemCode) *SubscriptionPlanVersionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedeemCodeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionPlanVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPlanVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionPlanVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPlanVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPlanVersionUpdate) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := subscriptionplanversion.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlanVersion.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidityUnit(); ok {
		if err := subscriptionplanversion.ValidityUnitValidator(v); err != nil {
			return &ValidationError{Name: "validity_unit", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlanVersion.validity_unit": %w`, err)}
		}
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionPlanVersion.plan"`)
	}
	return nil
}

func (_u *SubscriptionPlanVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionplanversion.Table, subscriptionplanversion.Columns, sqlgraph.NewFieldSpec(subscriptionplanversion.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(subscriptionplanversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(subscriptionplanversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(subscriptionplanversion.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(subscriptionplanversion.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(subscriptionplanversion.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(subscriptionplanversion.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OriginalPriceCleared() {
		_spec.ClearField(subscriptionplanversion.FieldOriginalPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(subscriptionplanversion.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(subscriptionplanversion.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(subscriptionplanversion.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidityUnit(); ok {
		_spec.SetField(subscriptionplanversion.FieldValidityUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(subscriptionplanversion.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(subscriptionplanversion.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdCleared() {
		_spec.ClearField(subscriptionplanversion.FieldDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(subscriptionplanversion.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyLimitUsd(); ok {
		_spec.AddField(subscriptionplanversion.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.WeeklyLimitUsdCleared() {
		_spec.ClearField(subscriptionplanversion.FieldWeeklyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(subscriptionplanversion.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(subscriptionplanversion.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdCleared() {
		_spec.ClearField(subscriptionplanversion.FieldMonthlyLimitUsd, field.TypeFloat64)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionplanversion.PlanTable,
			Columns: []string{subscriptionplanversion.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionplanversion.PlanTable,
			Columns: []string{subscriptionplanversion.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.SubscriptionsTable,
			Columns: []string{subscriptionplanversion.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.SubscriptionsTable,
			Columns: []string{subscriptionplanversion.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.SubscriptionsTable,
			Columns: []string{subscriptionplanversion.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.RedeemCodesTable,
			Columns: []string{subscriptionplanversion.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedeemCodesIDs(); len(nodes) > 0 && !_u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.RedeemCodesTable,
			Columns: []string{subscriptionplanversion.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.RedeemCodesTable,
			Columns: []string{subscriptionplanversion.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionplanversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionPlanVersionUpdateOne is the builder for updating a single SubscriptionPlanVersion entity.
type SubscriptionPlanVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionPlanVersionMutation
}

// SetPlanID sets the "plan_id" field.
func (_u *SubscriptionPlanVersionUpdateOne) SetPlanID(v int64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdateOne) SetNillablePlanID(v *int64) *SubscriptionPlanVersionUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *SubscriptionPlanVersionUpdateOne) SetVersion(v int) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdateOne) SetNillableVersion(v *int) *SubscriptionPlanVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *SubscriptionPlanVersionUpdateOne) AddVersion(v int) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *SubscriptionPlanVersionUpdateOne) SetPrice(v float64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdateOne) SetNillablePrice(v *float64) *SubscriptionPlanVersionUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *SubscriptionPlanVersionUpdateOne) AddPrice(v float64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *SubscriptionPlanVersionUpdateOne) SetOriginalPrice(v float64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdateOne) SetNillableOriginalPrice(v *float64) *SubscriptionPlanVersionUpdateOne {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *SubscriptionPlanVersionUpdateOne) AddOriginalPrice(v float64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (_u *SubscriptionPlanVersionUpdateOne) ClearOriginalPrice() *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ClearOriginalPrice()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *SubscriptionPlanVersionUpdateOne) SetCurrency(v string) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdateOne) SetNillableCurrency(v *string) *SubscriptionPlanVersionUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *SubscriptionPlanVersionUpdateOne) SetValidityDays(v int) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdateOne) SetNillableValidityDays(v *int) *SubscriptionPlanVersionUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *SubscriptionPlanVersionUpdateOne) AddValidityDays(v int) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetValidityUnit sets the "validity_unit" field.
func (_u *SubscriptionPlanVersionUpdateOne) SetValidityUnit(v string) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.SetValidityUnit(v)
	return _u
}

// SetNillableValidityUnit sets the "validity_unit" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdateOne) SetNillableValidityUnit(v *string) *SubscriptionPlanVersionUpdateOne {
	if v != nil {
		_u.SetValidityUnit(*v)
	}
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdateOne) SetDailyLimitUsd(v float64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdateOne) SetNillableDailyLimitUsd(v *float64) *SubscriptionPlanVersionUpdateOne {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdateOne) AddDailyLimitUsd(v float64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdateOne) ClearDailyLimitUsd() *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ClearDailyLimitUsd()
	return _u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdateOne) SetWeeklyLimitUsd(v float64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ResetWeeklyLimitUsd()
	_u.mutation.SetWeeklyLimitUsd(v)
	return _u
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdateOne) SetNillableWeeklyLimitUsd(v *float64) *SubscriptionPlanVersionUpdateOne {
	if v != nil {
		_u.SetWeeklyLimitUsd(*v)
	}
	return _u
}

// AddWeeklyLimitUsd adds value to the "weekly_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdateOne) AddWeeklyLimitUsd(v float64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.AddWeeklyLimitUsd(v)
	return _u
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdateOne) ClearWeeklyLimitUsd() *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ClearWeeklyLimitUsd()
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdateOne) SetMonthlyLimitUsd(v float64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanVersionUpdateOne) SetNillableMonthlyLimitUsd(v *float64) *SubscriptionPlanVersionUpdateOne {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdateOne) AddMonthlyLimitUsd(v float64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (_u *SubscriptionPlanVersionUpdateOne) ClearMonthlyLimitUsd() *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ClearMonthlyLimitUsd()
	return _u
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_u *SubscriptionPlanVersionUpdateOne) SetPlan(v *SubscriptionPlan) *SubscriptionPlanVersionUpdateOne {
	return _u.SetPlanID(v.ID)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (_u *SubscriptionPlanVersionUpdateOne) AddSubscriptionIDs(ids ...int64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (_u *SubscriptionPlanVersionUpdateOne) AddSubscriptions(v ...*UserSubscription) *SubscriptionPlanVersionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_u *SubscriptionPlanVersionUpdateOne) AddRedeemCodeIDs(ids ...int64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.AddRedeemCodeIDs(ids...)
	return _u
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_u *SubscriptionPlanVersionUpdateOne) AddRedeemCodes(v ...*RedeemCode) *SubscriptionPlanVersionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedeemCodeIDs(ids...)
}

// Mutation returns the SubscriptionPlanVersionMutation object of the builder.
func (_u *SubscriptionPlanVersionUpdateOne) Mutation() *SubscriptionPlanVersionMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the SubscriptionPlan entity.
func (_u *SubscriptionPlanVersionUpdateOne) ClearPlan() *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// ClearSubscriptions clears all "subscriptions" edges to the UserSubscription entity.
func (_u *SubscriptionPlanVersionUpdateOne) ClearSubscriptions() *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to UserSubscription entities by IDs.
func (_u *SubscriptionPlanVersionUpdateOne) RemoveSubscriptionIDs(ids ...int64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to UserSubscription entities.
func (_u *SubscriptionPlanVersionUpdateOne) RemoveSubscriptions(v ...*UserSubscription) *SubscriptionPlanVersionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearRedeemCodes clears all "redeem_codes" edges to the RedeemCode entity.
func (_u *SubscriptionPlanVersionUpdateOne) ClearRedeemCodes() *SubscriptionPlanVersionUpdateOne {
	_u.mutation.ClearRedeemCodes()
	return _u
}

// RemoveRedeemCodeIDs removes the "redeem_codes" edge to RedeemCode entities by IDs.
func (_u *SubscriptionPlanVersionUpdateOne) RemoveRedeemCodeIDs(ids ...int64) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.RemoveRedeemCodeIDs(ids...)
	return _u
}

// RemoveRedeemCodes removes "redeem_codes" edges to RedeemCode entities.
func (_u *SubscriptionPlanVersionUpdateOne) RemoveRedeemCodes(v ...*RedeemCode) *SubscriptionPlanVersionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedeemCodeIDs(ids...)
}

// Where appends a list predicates to the SubscriptionPlanVersionUpdate builder.
func (_u *SubscriptionPlanVersionUpdateOne) Where(ps ...predicate.SubscriptionPlanVersion) *SubscriptionPlanVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionPlanVersionUpdateOne) Select(field string, fields ...string) *SubscriptionPlanVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionPlanVersion entity.
func (_u *SubscriptionPlanVersionUpdateOne) Save(ctx context.Context) (*SubscriptionPlanVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPlanVersionUpdateOne) SaveX(ctx context.Context) *SubscriptionPlanVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionPlanVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPlanVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPlanVersionUpdateOne) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := subscriptionplanversion.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlanVersion.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidityUnit(); ok {
		if err := subscriptionplanversion.ValidityUnitValidator(v); err != nil {
			return &ValidationError{Name: "validity_unit", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlanVersion.validity_unit": %w`, err)}
		}
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionPlanVersion.plan"`)
	}
	return nil
}

func (_u *SubscriptionPlanVersionUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionPlanVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionplanversion.Table, subscriptionplanversion.Columns, sqlgraph.NewFieldSpec(subscriptionplanversion.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionPlanVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionplanversion.FieldID)
		for _, f := range fields {
			if !subscriptionplanversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionplanversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(subscriptionplanversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(subscriptionplanversion.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(subscriptionplanversion.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(subscriptionplanversion.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(subscriptionplanversion.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(subscriptionplanversion.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OriginalPriceCleared() {
		_spec.ClearField(subscriptionplanversion.FieldOriginalPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(subscriptionplanversion.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(subscriptionplanversion.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(subscriptionplanversion.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidityUnit(); ok {
		_spec.SetField(subscriptionplanversion.FieldValidityUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(subscriptionplanversion.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(subscriptionplanversion.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdCleared() {
		_spec.ClearField(subscriptionplanversion.FieldDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(subscriptionplanversion.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyLimitUsd(); ok {
		_spec.AddField(subscriptionplanversion.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.WeeklyLimitUsdCleared() {
		_spec.ClearField(subscriptionplanversion.FieldWeeklyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(subscriptionplanversion.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(subscriptionplanversion.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdCleared() {
		_spec.ClearField(subscriptionplanversion.FieldMonthlyLimitUsd, field.TypeFloat64)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionplanversion.PlanTable,
			Columns: []string{subscriptionplanversion.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionplanversion.PlanTable,
			Columns: []string{subscriptionplanversion.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.SubscriptionsTable,
			Columns: []string{subscriptionplanversion.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.SubscriptionsTable,
			Columns: []string{subscriptionplanversion.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.SubscriptionsTable,
			Columns: []string{subscriptionplanversion.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.RedeemCodesTable,
			Columns: []string{subscriptionplanversion.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedeemCodesIDs(); len(nodes) > 0 && !_u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.RedeemCodesTable,
			Columns: []string{subscriptionplanversion.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.RedeemCodesTable,
			Columns: []string{subscriptionplanversion.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionPlanVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionplanversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
