// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplanversion"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionPlanVersionCreate is the builder for creating a SubscriptionPlanVersion entity.
type SubscriptionPlanVersionCreate struct {
	config
	mutation *SubscriptionPlanVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPlanID sets the "plan_id" field.
func (_c *SubscriptionPlanVersionCreate) SetPlanID(v int64) *SubscriptionPlanVersionCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *SubscriptionPlanVersionCreate) SetVersion(v int) *SubscriptionPlanVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *SubscriptionPlanVersionCreate) SetPrice(v float64) *SubscriptionPlanVersionCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetOriginalPrice sets the "original_price" field.
func (_c *SubscriptionPlanVersionCreate) SetOriginalPrice(v float64) *SubscriptionPlanVersionCreate {
	_c.mutation.SetOriginalPrice(v)
	return _c
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_c *SubscriptionPlanVersionCreate) SetNillableOriginalPrice(v *float64) *SubscriptionPlanVersionCreate {
	if v != nil {
		_c.SetOriginalPrice(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *SubscriptionPlanVersionCreate) SetCurrency(v string) *SubscriptionPlanVersionCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *SubscriptionPlanVersionCreate) SetNillableCurrency(v *string) *SubscriptionPlanVersionCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *SubscriptionPlanVersionCreate) SetValidityDays(v int) *SubscriptionPlanVersionCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetValidityUnit sets the "validity_unit" field.
func (_c *SubscriptionPlanVersionCreate) SetValidityUnit(v string) *SubscriptionPlanVersionCreate {
	_c.mutation.SetValidityUnit(v)
	return _c
}

// SetNillableValidityUnit sets the "validity_unit" field if the given value is not nil.
func (_c *SubscriptionPlanVersionCreate) SetNillableValidityUnit(v *string) *SubscriptionPlanVersionCreate {
	if v != nil {
		_c.SetValidityUnit(*v)
	}
	return _c
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_c *SubscriptionPlanVersionCreate) SetDailyLimitUsd(v float64) *SubscriptionPlanVersionCreate {
	_c.mutation.SetDailyLimitUsd(v)
	return _c
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_c *SubscriptionPlanVersionCreate) SetNillableDailyLimitUsd(v *float64) *SubscriptionPlanVersionCreate {
	if v != nil {
		_c.SetDailyLimitUsd(*v)
	}
	return _c
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_c *SubscriptionPlanVersionCreate) SetWeeklyLimitUsd(v float64) *SubscriptionPlanVersionCreate {
	_c.mutation.SetWeeklyLimitUsd(v)
	return _c
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_c *SubscriptionPlanVersionCreate) SetNillableWeeklyLimitUsd(v *float64) *SubscriptionPlanVersionCreate {
	if v != nil {
		_c.SetWeeklyLimitUsd(*v)
	}
	return _c
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_c *SubscriptionPlanVersionCreate) SetMonthlyLimitUsd(v float64) *SubscriptionPlanVersionCreate {
	_c.mutation.SetMonthlyLimitUsd(v)
	return _c
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_c *SubscriptionPlanVersionCreate) SetNillableMonthlyLimitUsd(v *float64) *SubscriptionPlanVersionCreate {
	if v != nil {
		_c.SetMonthlyLimitUsd(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *SubscriptionPlanVersionCreate) SetPublishedAt(v time.Time) *SubscriptionPlanVersionCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *SubscriptionPlanVersionCreate) SetNillablePublishedAt(v *time.Time) *SubscriptionPlanVersionCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_c *SubscriptionPlanVersionCreate) SetPlan(v *SubscriptionPlan) *SubscriptionPlanVersionCreate {
	return _c.SetPlanID(v.ID)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (_c *SubscriptionPlanVersionCreate) AddSubscriptionIDs(ids ...int64) *SubscriptionPlanVersionCreate {
	_c.mutation.AddSubscriptionIDs(ids...)
	return _c
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (_c *SubscriptionPlanVersionCreate) AddSubscriptions(v ...*UserSubscription) *SubscriptionPlanVersionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubscriptionIDs(ids...)
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_c *SubscriptionPlanVersionCreate) AddRedeemCodeIDs(ids ...int64) *SubscriptionPlanVersionCreate {
	_c.mutation.AddRedeemCodeIDs(ids...)
	return _c
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_c *SubscriptionPlanVersionCreate) AddRedeemCodes(v ...*RedeemCode) *SubscriptionPlanVersionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRedeemCodeIDs(ids...)
}

// Mutation returns the SubscriptionPlanVersionMutation object of the builder.
func (_c *SubscriptionPlanVersionCreate) Mutation() *SubscriptionPlanVersionMutation {
	return _c.mutation
}

// Save creates the SubscriptionPlanVersion in the database.
func (_c *SubscriptionPlanVersionCreate) Save(ctx context.Context) (*SubscriptionPlanVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionPlanVersionCreate) SaveX(ctx context.Context) *SubscriptionPlanVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPlanVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPlanVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionPlanVersionCreate) defaults() {
	if _, ok := _c.mutation.Currency(); !ok {
		v := subscriptionplanversion.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.ValidityUnit(); !ok {
		v := subscriptionplanversion.DefaultValidityUnit
		_c.mutation.SetValidityUnit(v)
	}
	if _, ok := _c.mutation.PublishedAt(); !ok {
		v := subscriptionplanversion.DefaultPublishedAt()
		_c.mutation.SetPublishedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionPlanVersionCreate) check() error {
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "SubscriptionPlanVersion.plan_id"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "SubscriptionPlanVersion.version"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "SubscriptionPlanVersion.price"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "SubscriptionPlanVersion.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := subscriptionplanversion.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlanVersion.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		return &ValidationError{Name: "validity_days", err: errors.New(`ent: missing required field "SubscriptionPlanVersion.validity_days"`)}
	}
	if _, ok := _c.mutation.ValidityUnit(); !ok {
		return &ValidationError{Name: "validity_unit", err: errors.New(`ent: missing required field "SubscriptionPlanVersion.validity_unit"`)}
	}
	if v, ok := _c.mutation.ValidityUnit(); ok {
		if err := subscriptionplanversion.ValidityUnitValidator(v); err != nil {
			return &ValidationError{Name: "validity_unit", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlanVersion.validity_unit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublishedAt(); !ok {
		return &ValidationError{Name: "published_at", err: errors.New(`ent: missing required field "SubscriptionPlanVersion.published_at"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "SubscriptionPlanVersion.plan"`)}
	}
	return nil
}

func (_c *SubscriptionPlanVersionCreate) sqlSave(ctx context.Context) (*SubscriptionPlanVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionPlanVersionCreate) createSpec() (*SubscriptionPlanVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionPlanVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionplanversion.Table, sqlgraph.NewFieldSpec(subscriptionplanversion.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(subscriptionplanversion.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(subscriptionplanversion.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.OriginalPrice(); ok {
		_spec.SetField(subscriptionplanversion.FieldOriginalPrice, field.TypeFloat64, value)
		_node.OriginalPrice = &value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(subscriptionplanversion.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(subscriptionplanversion.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = value
	}
	if value, ok := _c.mutation.ValidityUnit(); ok {
		_spec.SetField(subscriptionplanversion.FieldValidityUnit, field.TypeString, value)
		_node.ValidityUnit = value
	}
	if value, ok := _c.mutation.DailyLimitUsd(); ok {
		_spec.SetField(subscriptionplanversion.FieldDailyLimitUsd, field.TypeFloat64, value)
		_node.DailyLimitUsd = &value
	}
	if value, ok := _c.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(subscriptionplanversion.FieldWeeklyLimitUsd, field.TypeFloat64, value)
		_node.WeeklyLimitUsd = &value
	}
	if value, ok := _c.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(subscriptionplanversion.FieldMonthlyLimitUsd, field.TypeFloat64, value)
		_node.MonthlyLimitUsd = &value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(subscriptionplanversion.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = value
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionplanversion.PlanTable,
			Columns: []string{subscriptionplanversion.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.SubscriptionsTable,
			Columns: []string{subscriptionplanversion.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplanversion.RedeemCodesTable,
			Columns: []string{subscriptionplanversion.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPlanVersion.Create().
//		SetPlanID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPlanVersionUpsert) {
//			SetPlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPlanVersionCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionPlanVersionUpsertOne {
	_c.conflict = opts
	return &SubscriptionPlanVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPlanVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPlanVersionCreate) OnConflictColumns(columns ...string) *SubscriptionPlanVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPlanVersionUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionPlanVersionUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionPlanVersion node.
	SubscriptionPlanVersionUpsertOne struct {
		create *SubscriptionPlanVersionCreate
	}

	// SubscriptionPlanVersionUpsert is the "OnConflict" setter.
	SubscriptionPlanVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionPlanVersionUpsert) SetPlanID(v int64) *SubscriptionPlanVersionUpsert {
	u.Set(subscriptionplanversion.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsert) UpdatePlanID() *SubscriptionPlanVersionUpsert {
	u.SetExcluded(subscriptionplanversion.FieldPlanID)
	return u
}

// SetVersion sets the "version" field.
func (u *SubscriptionPlanVersionUpsert) SetVersion(v int) *SubscriptionPlanVersionUpsert {
	u.Set(subscriptionplanversion.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsert) UpdateVersion() *SubscriptionPlanVersionUpsert {
	u.SetExcluded(subscriptionplanversion.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *SubscriptionPlanVersionUpsert) AddVersion(v int) *SubscriptionPlanVersionUpsert {
	u.Add(subscriptionplanversion.FieldVersion, v)
	return u
}

// SetPrice sets the "price" field.
func (u *SubscriptionPlanVersionUpsert) SetPrice(v float64) *SubscriptionPlanVersionUpsert {
	u.Set(subscriptionplanversion.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsert) UpdatePrice() *SubscriptionPlanVersionUpsert {
	u.SetExcluded(subscriptionplanversion.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *SubscriptionPlanVersionUpsert) AddPrice(v float64) *SubscriptionPlanVersionUpsert {
	u.Add(subscriptionplanversion.FieldPrice, v)
	return u
}

// SetOriginalPrice sets the "original_price" field.
func (u *SubscriptionPlanVersionUpsert) SetOriginalPrice(v float64) *SubscriptionPlanVersionUpsert {
	u.Set(subscriptionplanversion.FieldOriginalPrice, v)
	return u
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsert) UpdateOriginalPrice() *SubscriptionPlanVersionUpsert {
	u.SetExcluded(subscriptionplanversion.FieldOriginalPrice)
	return u
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *SubscriptionPlanVersionUpsert) AddOriginalPrice(v float64) *SubscriptionPlanVersionUpsert {
	u.Add(subscriptionplanversion.FieldOriginalPrice, v)
	return u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *SubscriptionPlanVersionUpsert) ClearOriginalPrice() *SubscriptionPlanVersionUpsert {
	u.SetNull(subscriptionplanversion.FieldOriginalPrice)
	return u
}

// SetCurrency sets the "currency" field.
func (u *SubscriptionPlanVersionUpsert) SetCurrency(v string) *SubscriptionPlanVersionUpsert {
	u.Set(subscriptionplanversion.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsert) UpdateCurrency() *SubscriptionPlanVersionUpsert {
	u.SetExcluded(subscriptionplanversion.FieldCurrency)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *SubscriptionPlanVersionUpsert) SetValidityDays(v int) *SubscriptionPlanVersionUpsert {
	u.Set(subscriptionplanversion.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsert) UpdateValidityDays() *SubscriptionPlanVersionUpsert {
	u.SetExcluded(subscriptionplanversion.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *SubscriptionPlanVersionUpsert) AddValidityDays(v int) *SubscriptionPlanVersionUpsert {
	u.Add(subscriptionplanversion.FieldValidityDays, v)
	return u
}

// SetValidityUnit sets the "validity_unit" field.
func (u *SubscriptionPlanVersionUpsert) SetValidityUnit(v string) *SubscriptionPlanVersionUpsert {
	u.Set(subscriptionplanversion.FieldValidityUnit, v)
	return u
}

// UpdateValidityUnit sets the "validity_unit" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsert) UpdateValidityUnit() *SubscriptionPlanVersionUpsert {
	u.SetExcluded(subscriptionplanversion.FieldValidityUnit)
	return u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *SubscriptionPlanVersionUpsert) SetDailyLimitUsd(v float64) *SubscriptionPlanVersionUpsert {
	u.Set(subscriptionplanversion.FieldDailyLimitUsd, v)
	return u
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsert) UpdateDailyLimitUsd() *SubscriptionPlanVersionUpsert {
	u.SetExcluded(subscriptionplanversion.FieldDailyLimitUsd)
	return u
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *SubscriptionPlanVersionUpsert) AddDailyLimitUsd(v float64) *SubscriptionPlanVersionUpsert {
	u.Add(subscriptionplanversion.FieldDailyLimitUsd, v)
	return u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *SubscriptionPlanVersionUpsert) ClearDailyLimitUsd() *SubscriptionPlanVersionUpsert {
	u.SetNull(subscriptionplanversion.FieldDailyLimitUsd)
	return u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsert) SetWeeklyLimitUsd(v float64) *SubscriptionPlanVersionUpsert {
	u.Set(subscriptionplanversion.FieldWeeklyLimitUsd, v)
	return u
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsert) UpdateWeeklyLimitUsd() *SubscriptionPlanVersionUpsert {
	u.SetExcluded(subscriptionplanversion.FieldWeeklyLimitUsd)
	return u
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsert) AddWeeklyLimitUsd(v float64) *SubscriptionPlanVersionUpsert {
	u.Add(subscriptionplanversion.FieldWeeklyLimitUsd, v)
	return u
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsert) ClearWeeklyLimitUsd() *SubscriptionPlanVersionUpsert {
	u.SetNull(subscriptionplanversion.FieldWeeklyLimitUsd)
	return u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsert) SetMonthlyLimitUsd(v float64) *SubscriptionPlanVersionUpsert {
	u.Set(subscriptionplanversion.FieldMonthlyLimitUsd, v)
	return u
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsert) UpdateMonthlyLimitUsd() *SubscriptionPlanVersionUpsert {
	u.SetExcluded(subscriptionplanversion.FieldMonthlyLimitUsd)
	return u
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsert) AddMonthlyLimitUsd(v float64) *SubscriptionPlanVersionUpsert {
	u.Add(subscriptionplanversion.FieldMonthlyLimitUsd, v)
	return u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsert) ClearMonthlyLimitUsd() *SubscriptionPlanVersionUpsert {
	u.SetNull(subscriptionplanversion.FieldMonthlyLimitUsd)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlanVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPlanVersionUpsertOne) UpdateNewValues() *SubscriptionPlanVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.PublishedAt(); exists {
			s.SetIgnore(subscriptionplanversion.FieldPublishedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlanVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionPlanVersionUpsertOne) Ignore() *SubscriptionPlanVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPlanVersionUpsertOne) DoNothing() *SubscriptionPlanVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPlanVersionCreate.OnConflict
// documentation for more info.
func (u *SubscriptionPlanVersionUpsertOne) Update(set func(*SubscriptionPlanVersionUpsert)) *SubscriptionPlanVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPlanVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionPlanVersionUpsertOne) SetPlanID(v int64) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertOne) UpdatePlanID() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdatePlanID()
	})
}

// SetVersion sets the "version" field.
func (u *SubscriptionPlanVersionUpsertOne) SetVersion(v int) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SubscriptionPlanVersionUpsertOne) AddVersion(v int) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertOne) UpdateVersion() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetPrice sets the "price" field.
func (u *SubscriptionPlanVersionUpsertOne) SetPrice(v float64) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *SubscriptionPlanVersionUpsertOne) AddPrice(v float64) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertOne) UpdatePrice() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdatePrice()
	})
}

// SetOriginalPrice sets the "original_price" field.
func (u *SubscriptionPlanVersionUpsertOne) SetOriginalPrice(v float64) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetOriginalPrice(v)
	})
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *SubscriptionPlanVersionUpsertOne) AddOriginalPrice(v float64) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddOriginalPrice(v)
	})
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertOne) UpdateOriginalPrice() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateOriginalPrice()
	})
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *SubscriptionPlanVersionUpsertOne) ClearOriginalPrice() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.ClearOriginalPrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *SubscriptionPlanVersionUpsertOne) SetCurrency(v string) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertOne) UpdateCurrency() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateCurrency()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *SubscriptionPlanVersionUpsertOne) SetValidityDays(v int) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *SubscriptionPlanVersionUpsertOne) AddValidityDays(v int) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertOne) UpdateValidityDays() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateValidityDays()
	})
}

// SetValidityUnit sets the "validity_unit" field.
func (u *SubscriptionPlanVersionUpsertOne) SetValidityUnit(v string) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetValidityUnit(v)
	})
}

// UpdateValidityUnit sets the "validity_unit" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertOne) UpdateValidityUnit() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateValidityUnit()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertOne) SetDailyLimitUsd(v float64) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertOne) AddDailyLimitUsd(v float64) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertOne) UpdateDailyLimitUsd() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertOne) ClearDailyLimitUsd() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.ClearDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertOne) SetWeeklyLimitUsd(v float64) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertOne) AddWeeklyLimitUsd(v float64) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertOne) UpdateWeeklyLimitUsd() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertOne) ClearWeeklyLimitUsd() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.ClearWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertOne) SetMonthlyLimitUsd(v float64) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertOne) AddMonthlyLimitUsd(v float64) *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertOne) UpdateMonthlyLimitUsd() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertOne) ClearMonthlyLimitUsd() *SubscriptionPlanVersionUpsertOne {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.ClearMonthlyLimitUsd()
	})
}

// Exec executes the query.
func (u *SubscriptionPlanVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPlanVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPlanVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionPlanVersionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionPlanVersionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionPlanVersionCreateBulk is the builder for creating many SubscriptionPlanVersion entities in bulk.
type SubscriptionPlanVersionCreateBulk struct {
	config
	err      error
	builders []*SubscriptionPlanVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionPlanVersion entities in the database.
func (_c *SubscriptionPlanVersionCreateBulk) Save(ctx context.Context) ([]*SubscriptionPlanVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionPlanVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionPlanVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionPlanVersionCreateBulk) SaveX(ctx context.Context) []*SubscriptionPlanVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPlanVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPlanVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPlanVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPlanVersionUpsert) {
//			SetPlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPlanVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionPlanVersionUpsertBulk {
	_c.conflict = opts
	return &SubscriptionPlanVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPlanVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPlanVersionCreateBulk) OnConflictColumns(columns ...string) *SubscriptionPlanVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPlanVersionUpsertBulk{
		create: _c,
	}
}

// SubscriptionPlanVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionPlanVersion nodes.
type SubscriptionPlanVersionUpsertBulk struct {
	create *SubscriptionPlanVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionPlanVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPlanVersionUpsertBulk) UpdateNewValues() *SubscriptionPlanVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.PublishedAt(); exists {
				s.SetIgnore(subscriptionplanversion.FieldPublishedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPlanVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionPlanVersionUpsertBulk) Ignore() *SubscriptionPlanVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPlanVersionUpsertBulk) DoNothing() *SubscriptionPlanVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPlanVersionCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionPlanVersionUpsertBulk) Update(set func(*SubscriptionPlanVersionUpsert)) *SubscriptionPlanVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPlanVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionPlanVersionUpsertBulk) SetPlanID(v int64) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertBulk) UpdatePlanID() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdatePlanID()
	})
}

// SetVersion sets the "version" field.
func (u *SubscriptionPlanVersionUpsertBulk) SetVersion(v int) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SubscriptionPlanVersionUpsertBulk) AddVersion(v int) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertBulk) UpdateVersion() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetPrice sets the "price" field.
func (u *SubscriptionPlanVersionUpsertBulk) SetPrice(v float64) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *SubscriptionPlanVersionUpsertBulk) AddPrice(v float64) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertBulk) UpdatePrice() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdatePrice()
	})
}

// SetOriginalPrice sets the "original_price" field.
func (u *SubscriptionPlanVersionUpsertBulk) SetOriginalPrice(v float64) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetOriginalPrice(v)
	})
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *SubscriptionPlanVersionUpsertBulk) AddOriginalPrice(v float64) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddOriginalPrice(v)
	})
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertBulk) UpdateOriginalPrice() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateOriginalPrice()
	})
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *SubscriptionPlanVersionUpsertBulk) ClearOriginalPrice() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.ClearOriginalPrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *SubscriptionPlanVersionUpsertBulk) SetCurrency(v string) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertBulk) UpdateCurrency() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateCurrency()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *SubscriptionPlanVersionUpsertBulk) SetValidityDays(v int) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *SubscriptionPlanVersionUpsertBulk) AddValidityDays(v int) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertBulk) UpdateValidityDays() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateValidityDays()
	})
}

// SetValidityUnit sets the "validity_unit" field.
func (u *SubscriptionPlanVersionUpsertBulk) SetValidityUnit(v string) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetValidityUnit(v)
	})
}

// UpdateValidityUnit sets the "validity_unit" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertBulk) UpdateValidityUnit() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateValidityUnit()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertBulk) SetDailyLimitUsd(v float64) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertBulk) AddDailyLimitUsd(v float64) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertBulk) UpdateDailyLimitUsd() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertBulk) ClearDailyLimitUsd() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.ClearDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertBulk) SetWeeklyLimitUsd(v float64) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertBulk) AddWeeklyLimitUsd(v float64) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertBulk) UpdateWeeklyLimitUsd() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertBulk) ClearWeeklyLimitUsd() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.ClearWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertBulk) SetMonthlyLimitUsd(v float64) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertBulk) AddMonthlyLimitUsd(v float64) *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *SubscriptionPlanVersionUpsertBulk) UpdateMonthlyLimitUsd() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *SubscriptionPlanVersionUpsertBulk) ClearMonthlyLimitUsd() *SubscriptionPlanVersionUpsertBulk {
	return u.Update(func(s *SubscriptionPlanVersionUpsert) {
		s.ClearMonthlyLimitUsd()
	})
}

// Exec executes the query.
func (u *SubscriptionPlanVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionPlanVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPlanVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPlanVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
