// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplanversion"
)

// SubscriptionPlanVersion is the model entity for the SubscriptionPlanVersion schema.
type SubscriptionPlanVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID int64 `json:"plan_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// OriginalPrice holds the value of the "original_price" field.
	OriginalPrice *float64 `json:"original_price,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// ValidityDays holds the value of the "validity_days" field.
	ValidityDays int `json:"validity_days,omitempty"`
	// ValidityUnit holds the value of the "validity_unit" field.
	ValidityUnit string `json:"validity_unit,omitempty"`
	// DailyLimitUsd holds the value of the "daily_limit_usd" field.
	DailyLimitUsd *float64 `json:"daily_limit_usd,omitempty"`
	// WeeklyLimitUsd holds the value of the "weekly_limit_usd" field.
	WeeklyLimitUsd *float64 `json:"weekly_limit_usd,omitempty"`
	// MonthlyLimitUsd holds the value of the "monthly_limit_usd" field.
	MonthlyLimitUsd *float64 `json:"monthly_limit_usd,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt time.Time `json:"published_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionPlanVersionQuery when eager-loading is set.
	Edges        SubscriptionPlanVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionPlanVersionEdges holds the relations/edges for other nodes in the graph.
type SubscriptionPlanVersionEdges struct {
	// Plan holds the value of the plan edge.
	Plan *SubscriptionPlan `json:"plan,omitempty"`
	// Subscriptions holds the value of the subscriptions edge.
	Subscriptions []*UserSubscription `json:"subscriptions,omitempty"`
	// RedeemCodes holds the value of the redeem_codes edge.
	RedeemCodes []*RedeemCode `json:"redeem_codes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionPlanVersionEdges) PlanOrErr() (*SubscriptionPlan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: subscriptionplan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// SubscriptionsOrErr returns the Subscriptions value or an error if the edge
// was not loaded in eager-loading.
func (e SubscriptionPlanVersionEdges) SubscriptionsOrErr() ([]*UserSubscription, error) {
	if e.loadedTypes[1] {
		return e.Subscriptions, nil
	}
	return nil, &NotLoadedError{edge: "subscriptions"}
}

// RedeemCodesOrErr returns the RedeemCodes value or an error if the edge
// was not loaded in eager-loading.
func (e SubscriptionPlanVersionEdges) RedeemCodesOrErr() ([]*RedeemCode, error) {
	if e.loadedTypes[2] {
		return e.RedeemCodes, nil
	}
	return nil, &NotLoadedError{edge: "redeem_codes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionPlanVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionplanversion.FieldPrice, subscriptionplanversion.FieldOriginalPrice, subscriptionplanversion.FieldDailyLimitUsd, subscriptionplanversion.FieldWeeklyLimitUsd, subscriptionplanversion.FieldMonthlyLimitUsd:
			values[i] = new(sql.NullFloat64)
		case subscriptionplanversion.FieldID, subscriptionplanversion.FieldPlanID, subscriptionplanversion.FieldVersion, subscriptionplanversion.FieldValidityDays:
			values[i] = new(sql.NullInt64)
		case subscriptionplanversion.FieldCurrency, subscriptionplanversion.FieldValidityUnit:
			values[i] = new(sql.NullString)
		case subscriptionplanversion.FieldPublishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionPlanVersion fields.
func (_m *SubscriptionPlanVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionplanversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionplanversion.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = value.Int64
			}
		case subscriptionplanversion.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case subscriptionplanversion.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case subscriptionplanversion.FieldOriginalPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field original_price", values[i])
			} else if value.Valid {
				_m.OriginalPrice = new(float64)
				*_m.OriginalPrice = value.Float64
			}
		case subscriptionplanversion.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case subscriptionplanversion.FieldValidityDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field validity_days", values[i])
			} else if value.Valid {
				_m.ValidityDays = int(value.Int64)
			}
		case subscriptionplanversion.FieldValidityUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field validity_unit", values[i])
			} else if value.Valid {
				_m.ValidityUnit = value.String
			}
		case subscriptionplanversion.FieldDailyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_usd", values[i])
			} else if value.Valid {
				_m.DailyLimitUsd = new(float64)
				*_m.DailyLimitUsd = value.Float64
			}
		case subscriptionplanversion.FieldWeeklyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_limit_usd", values[i])
			} else if value.Valid {
				_m.WeeklyLimitUsd = new(float64)
				*_m.WeeklyLimitUsd = value.Float64
			}
		case subscriptionplanversion.FieldMonthlyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_limit_usd", values[i])
			} else if value.Valid {
				_m.MonthlyLimitUsd = new(float64)
				*_m.MonthlyLimitUsd = value.Float64
			}
		case subscriptionplanversion.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionPlanVersion.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionPlanVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlan queries the "plan" edge of the SubscriptionPlanVersion entity.
func (_m *SubscriptionPlanVersion) QueryPlan() *SubscriptionPlanQuery {
	return NewSubscriptionPlanVersionClient(_m.config).QueryPlan(_m)
}

// QuerySubscriptions queries the "subscriptions" edge of the SubscriptionPlanVersion entity.
func (_m *SubscriptionPlanVersion) QuerySubscriptions() *UserSubscriptionQuery {
	return NewSubscriptionPlanVersionClient(_m.config).QuerySubscriptions(_m)
}

// QueryRedeemCodes queries the "redeem_codes" edge of the SubscriptionPlanVersion entity.
func (_m *SubscriptionPlanVersion) QueryRedeemCodes() *RedeemCodeQuery {
	return NewSubscriptionPlanVersionClient(_m.config).QueryRedeemCodes(_m)
}

// Update returns a builder for updating this SubscriptionPlanVersion.
// Note that you need to call SubscriptionPlanVersion.Unwrap() before calling this method if this SubscriptionPlanVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionPlanVersion) Update() *SubscriptionPlanVersionUpdateOne {
	return NewSubscriptionPlanVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionPlanVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionPlanVersion) Unwrap() *SubscriptionPlanVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionPlanVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionPlanVersion) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionPlanVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	if v := _m.OriginalPrice; v != nil {
		builder.WriteString("original_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("validity_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValidityDays))
	builder.WriteString(", ")
	builder.WriteString("validity_unit=")
	builder.WriteString(_m.ValidityUnit)
	builder.WriteString(", ")
	if v := _m.DailyLimitUsd; v != nil {
		builder.WriteString("daily_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.WeeklyLimitUsd; v != nil {
		builder.WriteString("weekly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MonthlyLimitUsd; v != nil {
		builder.WriteString("monthly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("published_at=")
	builder.WriteString(_m.PublishedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionPlanVersions is a parsable slice of SubscriptionPlanVersion.
type SubscriptionPlanVersions []*SubscriptionPlanVersion
