// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplanversion"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionPlanVersionQuery is the builder for querying SubscriptionPlanVersion entities.
type SubscriptionPlanVersionQuery struct {
	config
	ctx               *QueryContext
	order             []subscriptionplanversion.OrderOption
	inters            []Interceptor
	predicates        []predicate.SubscriptionPlanVersion
	withPlan          *SubscriptionPlanQuery
	withSubscriptions *UserSubscriptionQuery
	withRedeemCodes   *RedeemCodeQuery
	modifiers         []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubscriptionPlanVersionQuery builder.
func (_q *SubscriptionPlanVersionQuery) Where(ps ...predicate.SubscriptionPlanVersion) *SubscriptionPlanVersionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SubscriptionPlanVersionQuery) Limit(limit int) *SubscriptionPlanVersionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SubscriptionPlanVersionQuery) Offset(offset int) *SubscriptionPlanVersionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SubscriptionPlanVersionQuery) Unique(unique bool) *SubscriptionPlanVersionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SubscriptionPlanVersionQuery) Order(o ...subscriptionplanversion.OrderOption) *SubscriptionPlanVersionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPlan chains the current query on the "plan" edge.
func (_q *SubscriptionPlanVersionQuery) QueryPlan() *SubscriptionPlanQuery {
	query := (&SubscriptionPlanClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionplanversion.Table, subscriptionplanversion.FieldID, selector),
			sqlgraph.To(subscriptionplan.Table, subscriptionplan.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionplanversion.PlanTable, subscriptionplanversion.PlanColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubscriptions chains the current query on the "subscriptions" edge.
func (_q *SubscriptionPlanVersionQuery) QuerySubscriptions() *UserSubscriptionQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionplanversion.Table, subscriptionplanversion.FieldID, selector),
			sqlgraph.To(usersubscription.Table, usersubscription.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, subscriptionplanversion.SubscriptionsTable, subscriptionplanversion.SubscriptionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRedeemCodes chains the current query on the "redeem_codes" edge.
func (_q *SubscriptionPlanVersionQuery) QueryRedeemCodes() *RedeemCodeQuery {
	query := (&RedeemCodeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionplanversion.Table, subscriptionplanversion.FieldID, selector),
			sqlgraph.To(redeemcode.Table, redeemcode.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, subscriptionplanversion.RedeemCodesTable, subscriptionplanversion.RedeemCodesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SubscriptionPlanVersion entity from the query.
// Returns a *NotFoundError when no SubscriptionPlanVersion was found.
func (_q *SubscriptionPlanVersionQuery) First(ctx context.Context) (*SubscriptionPlanVersion, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subscriptionplanversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SubscriptionPlanVersionQuery) FirstX(ctx context.Context) *SubscriptionPlanVersion {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubscriptionPlanVersion ID from the query.
// Returns a *NotFoundError when no SubscriptionPlanVersion ID was found.
func (_q *SubscriptionPlanVersionQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subscriptionplanversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SubscriptionPlanVersionQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubscriptionPlanVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubscriptionPlanVersion entity is found.
// Returns a *NotFoundError when no SubscriptionPlanVersion entities are found.
func (_q *SubscriptionPlanVersionQuery) Only(ctx context.Context) (*SubscriptionPlanVersion, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subscriptionplanversion.Label}
	default:
		return nil, &NotSingularError{subscriptionplanversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SubscriptionPlanVersionQuery) OnlyX(ctx context.Context) *SubscriptionPlanVersion {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubscriptionPlanVersion ID in the query.
// Returns a *NotSingularError when more than one SubscriptionPlanVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SubscriptionPlanVersionQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subscriptionplanversion.Label}
	default:
		err = &NotSingularError{subscriptionplanversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SubscriptionPlanVersionQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubscriptionPlanVersions.
func (_q *SubscriptionPlanVersionQuery) All(ctx context.Context) ([]*SubscriptionPlanVersion, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubscriptionPlanVersion, *SubscriptionPlanVersionQuery]()
	return withInterceptors[[]*SubscriptionPlanVersion](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SubscriptionPlanVersionQuery) AllX(ctx context.Context) []*SubscriptionPlanVersion {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubscriptionPlanVersion IDs.
func (_q *SubscriptionPlanVersionQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(subscriptionplanversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SubscriptionPlanVersionQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SubscriptionPlanVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SubscriptionPlanVersionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SubscriptionPlanVersionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SubscriptionPlanVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SubscriptionPlanVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubscriptionPlanVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SubscriptionPlanVersionQuery) Clone() *SubscriptionPlanVersionQuery {
	if _q == nil {
		return nil
	}
	return &SubscriptionPlanVersionQuery{
		config:            _q.config,
		ctx:               _q.ctx.Clone(),
		order:             append([]subscriptionplanversion.OrderOption{}, _q.order...),
		inters:            append([]Interceptor{}, _q.inters...),
		predicates:        append([]predicate.SubscriptionPlanVersion{}, _q.predicates...),
		withPlan:          _q.withPlan.Clone(),
		withSubscriptions: _q.withSubscriptions.Clone(),
		withRedeemCodes:   _q.withRedeemCodes.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPlan tells the query-builder to eager-load the nodes that are connected to
// the "plan" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionPlanVersionQuery) WithPlan(opts ...func(*SubscriptionPlanQuery)) *SubscriptionPlanVersionQuery {
	query := (&SubscriptionPlanClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPlan = query
	return _q
}

// WithSubscriptions tells the query-builder to eager-load the nodes that are connected to
// the "subscriptions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionPlanVersionQuery) WithSubscriptions(opts ...func(*UserSubscriptionQuery)) *SubscriptionPlanVersionQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSubscriptions = query
	return _q
}

// WithRedeemCodes tells the query-builder to eager-load the nodes that are connected to
// the "redeem_codes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionPlanVersionQuery) WithRedeemCodes(opts ...func(*RedeemCodeQuery)) *SubscriptionPlanVersionQuery {
	query := (&RedeemCodeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRedeemCodes = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PlanID int64 `json:"plan_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubscriptionPlanVersion.Query().
//		GroupBy(subscriptionplanversion.FieldPlanID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SubscriptionPlanVersionQuery) GroupBy(field string, fields ...string) *SubscriptionPlanVersionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubscriptionPlanVersionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = subscriptionplanversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PlanID int64 `json:"plan_id,omitempty"`
//	}
//
//	client.SubscriptionPlanVersion.Query().
//		Select(subscriptionplanversion.FieldPlanID).
//		Scan(ctx, &v)
func (_q *SubscriptionPlanVersionQuery) Select(fields ...string) *SubscriptionPlanVersionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SubscriptionPlanVersionSelect{SubscriptionPlanVersionQuery: _q}
	sbuild.label = subscriptionplanversion.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubscriptionPlanVersionSelect configured with the given aggregations.
func (_q *SubscriptionPlanVersionQuery) Aggregate(fns ...AggregateFunc) *SubscriptionPlanVersionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SubscriptionPlanVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !subscriptionplanversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SubscriptionPlanVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubscriptionPlanVersion, error) {
	var (
		nodes       = []*SubscriptionPlanVersion{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withPlan != nil,
			_q.withSubscriptions != nil,
			_q.withRedeemCodes != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubscriptionPlanVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubscriptionPlanVersion{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPlan; query != nil {
		if err := _q.loadPlan(ctx, query, nodes, nil,
			func(n *SubscriptionPlanVersion, e *SubscriptionPlan) { n.Edges.Plan = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSubscriptions; query != nil {
		if err := _q.loadSubscriptions(ctx, query, nodes,
			func(n *SubscriptionPlanVersion) { n.Edges.Subscriptions = []*UserSubscription{} },
			func(n *SubscriptionPlanVersion, e *UserSubscription) {
				n.Edges.Subscriptions = append(n.Edges.Subscriptions, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withRedeemCodes; query != nil {
		if err := _q.loadRedeemCodes(ctx, query, nodes,
			func(n *SubscriptionPlanVersion) { n.Edges.RedeemCodes = []*RedeemCode{} },
			func(n *SubscriptionPlanVersion, e *RedeemCode) { n.Edges.RedeemCodes = append(n.Edges.RedeemCodes, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SubscriptionPlanVersionQuery) loadPlan(ctx context.Context, query *SubscriptionPlanQuery, nodes []*SubscriptionPlanVersion, init func(*SubscriptionPlanVersion), assign func(*SubscriptionPlanVersion, *SubscriptionPlan)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionPlanVersion)
	for i := range nodes {
		fk := nodes[i].PlanID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(subscriptionplan.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "plan_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionPlanVersionQuery) loadSubscriptions(ctx context.Context, query *UserSubscriptionQuery, nodes []*SubscriptionPlanVersion, init func(*SubscriptionPlanVersion), assign func(*SubscriptionPlanVersion, *UserSubscription)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*SubscriptionPlanVersion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(usersubscription.FieldPlanVersionID)
	}
	query.Where(predicate.UserSubscription(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(subscriptionplanversion.SubscriptionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PlanVersionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "plan_version_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *SubscriptionPlanVersionQuery) loadRedeemCodes(ctx context.Context, query *RedeemCodeQuery, nodes []*SubscriptionPlanVersion, init func(*SubscriptionPlanVersion), assign func(*SubscriptionPlanVersion, *RedeemCode)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*SubscriptionPlanVersion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(redeemcode.FieldPlanVersionID)
	}
	query.Where(predicate.RedeemCode(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(subscriptionplanversion.RedeemCodesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PlanVersionID
		if fk == nil {
			return fmt.Errorf(`foreign-key "plan_version_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "plan_version_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SubscriptionPlanVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SubscriptionPlanVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subscriptionplanversion.Table, subscriptionplanversion.Columns, sqlgraph.NewFieldSpec(subscriptionplanversion.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionplanversion.FieldID)
		for i := range fields {
			if fields[i] != subscriptionplanversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withPlan != nil {
			_spec.Node.AddColumnOnce(subscriptionplanversion.FieldPlanID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SubscriptionPlanVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(subscriptionplanversion.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = subscriptionplanversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SubscriptionPlanVersionQuery) ForUpdate(opts ...sql.LockOption) *SubscriptionPlanVersionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SubscriptionPlanVersionQuery) ForShare(opts ...sql.LockOption) *SubscriptionPlanVersionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// SubscriptionPlanVersionGroupBy is the group-by builder for SubscriptionPlanVersion entities.
type SubscriptionPlanVersionGroupBy struct {
	selector
	build *SubscriptionPlanVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SubscriptionPlanVersionGroupBy) Aggregate(fns ...AggregateFunc) *SubscriptionPlanVersionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SubscriptionPlanVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionPlanVersionQuery, *SubscriptionPlanVersionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SubscriptionPlanVersionGroupBy) sqlScan(ctx context.Context, root *SubscriptionPlanVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubscriptionPlanVersionSelect is the builder for selecting fields of SubscriptionPlanVersion entities.
type SubscriptionPlanVersionSelect struct {
	*SubscriptionPlanVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SubscriptionPlanVersionSelect) Aggregate(fns ...AggregateFunc) *SubscriptionPlanVersionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SubscriptionPlanVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionPlanVersionQuery, *SubscriptionPlanVersionSelect](ctx, _s.SubscriptionPlanVersionQuery, _s, _s.inters, v)
}

func (_s *SubscriptionPlanVersionSelect) sqlScan(ctx context.Context, root *SubscriptionPlanVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
