// Code generated by ent, DO NOT EDIT.

package billingreservation

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the billingreservation type in the database.
	Label = "billing_reservation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldFundingSource holds the string denoting the funding_source field in the database.
	FieldFundingSource = "funding_source"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldAuthorizedAmount holds the string denoting the authorized_amount field in the database.
	FieldAuthorizedAmount = "authorized_amount"
	// FieldCapturedAmount holds the string denoting the captured_amount field in the database.
	FieldCapturedAmount = "captured_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAuthorizationFingerprint holds the string denoting the authorization_fingerprint field in the database.
	FieldAuthorizationFingerprint = "authorization_fingerprint"
	// FieldRequestFingerprint holds the string denoting the request_fingerprint field in the database.
	FieldRequestFingerprint = "request_fingerprint"
	// FieldDailyWindowStart holds the string denoting the daily_window_start field in the database.
	FieldDailyWindowStart = "daily_window_start"
	// FieldWeeklyWindowStart holds the string denoting the weekly_window_start field in the database.
	FieldWeeklyWindowStart = "weekly_window_start"
	// FieldMonthlyWindowStart holds the string denoting the monthly_window_start field in the database.
	FieldMonthlyWindowStart = "monthly_window_start"
	// FieldAsyncTaskID holds the string denoting the async_task_id field in the database.
	FieldAsyncTaskID = "async_task_id"
	// FieldAsyncMetadata holds the string denoting the async_metadata field in the database.
	FieldAsyncMetadata = "async_metadata"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the billingreservation in the database.
	Table = "billing_reservations"
)

// Columns holds all SQL columns for billingreservation fields.
var Columns = []string{
	FieldID,
	FieldRequestID,
	FieldAPIKeyID,
	FieldUserID,
	FieldFundingSource,
	FieldSubscriptionID,
	FieldAuthorizedAmount,
	FieldCapturedAmount,
	FieldStatus,
	FieldAuthorizationFingerprint,
	FieldRequestFingerprint,
	FieldDailyWindowStart,
	FieldWeeklyWindowStart,
	FieldMonthlyWindowStart,
	FieldAsyncTaskID,
	FieldAsyncMetadata,
	FieldExpiresAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// FundingSourceValidator is a validator for the "funding_source" field. It is called by the builders before save.
	FundingSourceValidator func(string) error
	// DefaultAuthorizedAmount holds the default value on creation for the "authorized_amount" field.
	DefaultAuthorizedAmount float64
	// DefaultCapturedAmount holds the default value on creation for the "captured_amount" field.
	DefaultCapturedAmount float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// AuthorizationFingerprintValidator is a validator for the "authorization_fingerprint" field. It is called by the builders before save.
	AuthorizationFingerprintValidator func(string) error
	// DefaultRequestFingerprint holds the default value on creation for the "request_fingerprint" field.
	DefaultRequestFingerprint string
	// RequestFingerprintValidator is a validator for the "request_fingerprint" field. It is called by the builders before save.
	RequestFingerprintValidator func(string) error
	// AsyncTaskIDValidator is a validator for the "async_task_id" field. It is called by the builders before save.
	AsyncTaskIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the BillingReservation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByFundingSource orders the results by the funding_source field.
func ByFundingSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFundingSource, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// ByAuthorizedAmount orders the results by the authorized_amount field.
func ByAuthorizedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorizedAmount, opts...).ToFunc()
}

// ByCapturedAmount orders the results by the captured_amount field.
func ByCapturedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAuthorizationFingerprint orders the results by the authorization_fingerprint field.
func ByAuthorizationFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorizationFingerprint, opts...).ToFunc()
}

// ByRequestFingerprint orders the results by the request_fingerprint field.
func ByRequestFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestFingerprint, opts...).ToFunc()
}

// ByDailyWindowStart orders the results by the daily_window_start field.
func ByDailyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyWindowStart, opts...).ToFunc()
}

// ByWeeklyWindowStart orders the results by the weekly_window_start field.
func ByWeeklyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyWindowStart, opts...).ToFunc()
}

// ByMonthlyWindowStart orders the results by the monthly_window_start field.
func ByMonthlyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyWindowStart, opts...).ToFunc()
}

// ByAsyncTaskID orders the results by the async_task_id field.
func ByAsyncTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAsyncTaskID, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
