// Code generated by ent, DO NOT EDIT.

package billingreservation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldRequestID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldAPIKeyID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldUserID, v))
}

// FundingSource applies equality check predicate on the "funding_source" field. It's identical to FundingSourceEQ.
func FundingSource(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldFundingSource, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldSubscriptionID, v))
}

// AuthorizedAmount applies equality check predicate on the "authorized_amount" field. It's identical to AuthorizedAmountEQ.
func AuthorizedAmount(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldAuthorizedAmount, v))
}

// CapturedAmount applies equality check predicate on the "captured_amount" field. It's identical to CapturedAmountEQ.
func CapturedAmount(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldCapturedAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldStatus, v))
}

// AuthorizationFingerprint applies equality check predicate on the "authorization_fingerprint" field. It's identical to AuthorizationFingerprintEQ.
func AuthorizationFingerprint(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldAuthorizationFingerprint, v))
}

// RequestFingerprint applies equality check predicate on the "request_fingerprint" field. It's identical to RequestFingerprintEQ.
func RequestFingerprint(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldRequestFingerprint, v))
}

// DailyWindowStart applies equality check predicate on the "daily_window_start" field. It's identical to DailyWindowStartEQ.
func DailyWindowStart(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldDailyWindowStart, v))
}

// WeeklyWindowStart applies equality check predicate on the "weekly_window_start" field. It's identical to WeeklyWindowStartEQ.
func WeeklyWindowStart(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldWeeklyWindowStart, v))
}

// MonthlyWindowStart applies equality check predicate on the "monthly_window_start" field. It's identical to MonthlyWindowStartEQ.
func MonthlyWindowStart(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldMonthlyWindowStart, v))
}

// AsyncTaskID applies equality check predicate on the "async_task_id" field. It's identical to AsyncTaskIDEQ.
func AsyncTaskID(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldAsyncTaskID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldUpdatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldContainsFold(FieldRequestID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldAPIKeyID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldUserID, v))
}

// FundingSourceEQ applies the EQ predicate on the "funding_source" field.
func FundingSourceEQ(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldFundingSource, v))
}

// FundingSourceNEQ applies the NEQ predicate on the "funding_source" field.
func FundingSourceNEQ(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldFundingSource, v))
}

// FundingSourceIn applies the In predicate on the "funding_source" field.
func FundingSourceIn(vs ...string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldFundingSource, vs...))
}

// FundingSourceNotIn applies the NotIn predicate on the "funding_source" field.
func FundingSourceNotIn(vs ...string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldFundingSource, vs...))
}

// FundingSourceGT applies the GT predicate on the "funding_source" field.
func FundingSourceGT(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldFundingSource, v))
}

// FundingSourceGTE applies the GTE predicate on the "funding_source" field.
func FundingSourceGTE(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldFundingSource, v))
}

// FundingSourceLT applies the LT predicate on the "funding_source" field.
func FundingSourceLT(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldFundingSource, v))
}

// FundingSourceLTE applies the LTE predicate on the "funding_source" field.
func FundingSourceLTE(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldFundingSource, v))
}

// FundingSourceContains applies the Contains predicate on the "funding_source" field.
func FundingSourceContains(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldContains(FieldFundingSource, v))
}

// FundingSourceHasPrefix applies the HasPrefix predicate on the "funding_source" field.
func FundingSourceHasPrefix(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldHasPrefix(FieldFundingSource, v))
}

// FundingSourceHasSuffix applies the HasSuffix predicate on the "funding_source" field.
func FundingSourceHasSuffix(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldHasSuffix(FieldFundingSource, v))
}

// FundingSourceEqualFold applies the EqualFold predicate on the "funding_source" field.
func FundingSourceEqualFold(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEqualFold(FieldFundingSource, v))
}

// FundingSourceContainsFold applies the ContainsFold predicate on the "funding_source" field.
func FundingSourceContainsFold(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldContainsFold(FieldFundingSource, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDGT applies the GT predicate on the "subscription_id" field.
func SubscriptionIDGT(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldSubscriptionID, v))
}

// SubscriptionIDGTE applies the GTE predicate on the "subscription_id" field.
func SubscriptionIDGTE(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldSubscriptionID, v))
}

// SubscriptionIDLT applies the LT predicate on the "subscription_id" field.
func SubscriptionIDLT(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldSubscriptionID, v))
}

// SubscriptionIDLTE applies the LTE predicate on the "subscription_id" field.
func SubscriptionIDLTE(v int64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldSubscriptionID, v))
}

// SubscriptionIDIsNil applies the IsNil predicate on the "subscription_id" field.
func SubscriptionIDIsNil() predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIsNull(FieldSubscriptionID))
}

// SubscriptionIDNotNil applies the NotNil predicate on the "subscription_id" field.
func SubscriptionIDNotNil() predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotNull(FieldSubscriptionID))
}

// AuthorizedAmountEQ applies the EQ predicate on the "authorized_amount" field.
func AuthorizedAmountEQ(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldAuthorizedAmount, v))
}

// AuthorizedAmountNEQ applies the NEQ predicate on the "authorized_amount" field.
func AuthorizedAmountNEQ(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldAuthorizedAmount, v))
}

// AuthorizedAmountIn applies the In predicate on the "authorized_amount" field.
func AuthorizedAmountIn(vs ...float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldAuthorizedAmount, vs...))
}

// AuthorizedAmountNotIn applies the NotIn predicate on the "authorized_amount" field.
func AuthorizedAmountNotIn(vs ...float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldAuthorizedAmount, vs...))
}

// AuthorizedAmountGT applies the GT predicate on the "authorized_amount" field.
func AuthorizedAmountGT(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldAuthorizedAmount, v))
}

// AuthorizedAmountGTE applies the GTE predicate on the "authorized_amount" field.
func AuthorizedAmountGTE(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldAuthorizedAmount, v))
}

// AuthorizedAmountLT applies the LT predicate on the "authorized_amount" field.
func AuthorizedAmountLT(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldAuthorizedAmount, v))
}

// AuthorizedAmountLTE applies the LTE predicate on the "authorized_amount" field.
func AuthorizedAmountLTE(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldAuthorizedAmount, v))
}

// CapturedAmountEQ applies the EQ predicate on the "captured_amount" field.
func CapturedAmountEQ(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldCapturedAmount, v))
}

// CapturedAmountNEQ applies the NEQ predicate on the "captured_amount" field.
func CapturedAmountNEQ(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldCapturedAmount, v))
}

// CapturedAmountIn applies the In predicate on the "captured_amount" field.
func CapturedAmountIn(vs ...float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldCapturedAmount, vs...))
}

// CapturedAmountNotIn applies the NotIn predicate on the "captured_amount" field.
func CapturedAmountNotIn(vs ...float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldCapturedAmount, vs...))
}

// CapturedAmountGT applies the GT predicate on the "captured_amount" field.
func CapturedAmountGT(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldCapturedAmount, v))
}

// CapturedAmountGTE applies the GTE predicate on the "captured_amount" field.
func CapturedAmountGTE(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldCapturedAmount, v))
}

// CapturedAmountLT applies the LT predicate on the "captured_amount" field.
func CapturedAmountLT(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldCapturedAmount, v))
}

// CapturedAmountLTE applies the LTE predicate on the "captured_amount" field.
func CapturedAmountLTE(v float64) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldCapturedAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldContainsFold(FieldStatus, v))
}

// AuthorizationFingerprintEQ applies the EQ predicate on the "authorization_fingerprint" field.
func AuthorizationFingerprintEQ(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldAuthorizationFingerprint, v))
}

// AuthorizationFingerprintNEQ applies the NEQ predicate on the "authorization_fingerprint" field.
func AuthorizationFingerprintNEQ(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldAuthorizationFingerprint, v))
}

// AuthorizationFingerprintIn applies the In predicate on the "authorization_fingerprint" field.
func AuthorizationFingerprintIn(vs ...string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldAuthorizationFingerprint, vs...))
}

// AuthorizationFingerprintNotIn applies the NotIn predicate on the "authorization_fingerprint" field.
func AuthorizationFingerprintNotIn(vs ...string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldAuthorizationFingerprint, vs...))
}

// AuthorizationFingerprintGT applies the GT predicate on the "authorization_fingerprint" field.
func AuthorizationFingerprintGT(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldAuthorizationFingerprint, v))
}

// AuthorizationFingerprintGTE applies the GTE predicate on the "authorization_fingerprint" field.
func AuthorizationFingerprintGTE(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldAuthorizationFingerprint, v))
}

// AuthorizationFingerprintLT applies the LT predicate on the "authorization_fingerprint" field.
func AuthorizationFingerprintLT(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldAuthorizationFingerprint, v))
}

// AuthorizationFingerprintLTE applies the LTE predicate on the "authorization_fingerprint" field.
func AuthorizationFingerprintLTE(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldAuthorizationFingerprint, v))
}

// AuthorizationFingerprintContains applies the Contains predicate on the "authorization_fingerprint" field.
func AuthorizationFingerprintContains(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldContains(FieldAuthorizationFingerprint, v))
}

// AuthorizationFingerprintHasPrefix applies the HasPrefix predicate on the "authorization_fingerprint" field.
func AuthorizationFingerprintHasPrefix(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldHasPrefix(FieldAuthorizationFingerprint, v))
}

// AuthorizationFingerprintHasSuffix applies the HasSuffix predicate on the "authorization_fingerprint" field.
func AuthorizationFingerprintHasSuffix(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldHasSuffix(FieldAuthorizationFingerprint, v))
}

// AuthorizationFingerprintEqualFold applies the EqualFold predicate on the "authorization_fingerprint" field.
func AuthorizationFingerprintEqualFold(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEqualFold(FieldAuthorizationFingerprint, v))
}

// AuthorizationFingerprintContainsFold applies the ContainsFold predicate on the "authorization_fingerprint" field.
func AuthorizationFingerprintContainsFold(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldContainsFold(FieldAuthorizationFingerprint, v))
}

// RequestFingerprintEQ applies the EQ predicate on the "request_fingerprint" field.
func RequestFingerprintEQ(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintNEQ applies the NEQ predicate on the "request_fingerprint" field.
func RequestFingerprintNEQ(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintIn applies the In predicate on the "request_fingerprint" field.
func RequestFingerprintIn(vs ...string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintNotIn applies the NotIn predicate on the "request_fingerprint" field.
func RequestFingerprintNotIn(vs ...string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintGT applies the GT predicate on the "request_fingerprint" field.
func RequestFingerprintGT(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldRequestFingerprint, v))
}

// RequestFingerprintGTE applies the GTE predicate on the "request_fingerprint" field.
func RequestFingerprintGTE(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldRequestFingerprint, v))
}

// RequestFingerprintLT applies the LT predicate on the "request_fingerprint" field.
func RequestFingerprintLT(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldRequestFingerprint, v))
}

// RequestFingerprintLTE applies the LTE predicate on the "request_fingerprint" field.
func RequestFingerprintLTE(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldRequestFingerprint, v))
}

// RequestFingerprintContains applies the Contains predicate on the "request_fingerprint" field.
func RequestFingerprintContains(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldContains(FieldRequestFingerprint, v))
}

// RequestFingerprintHasPrefix applies the HasPrefix predicate on the "request_fingerprint" field.
func RequestFingerprintHasPrefix(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldHasPrefix(FieldRequestFingerprint, v))
}

// RequestFingerprintHasSuffix applies the HasSuffix predicate on the "request_fingerprint" field.
func RequestFingerprintHasSuffix(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldHasSuffix(FieldRequestFingerprint, v))
}

// RequestFingerprintEqualFold applies the EqualFold predicate on the "request_fingerprint" field.
func RequestFingerprintEqualFold(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEqualFold(FieldRequestFingerprint, v))
}

// RequestFingerprintContainsFold applies the ContainsFold predicate on the "request_fingerprint" field.
func RequestFingerprintContainsFold(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldContainsFold(FieldRequestFingerprint, v))
}

// DailyWindowStartEQ applies the EQ predicate on the "daily_window_start" field.
func DailyWindowStartEQ(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldDailyWindowStart, v))
}

// DailyWindowStartNEQ applies the NEQ predicate on the "daily_window_start" field.
func DailyWindowStartNEQ(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldDailyWindowStart, v))
}

// DailyWindowStartIn applies the In predicate on the "daily_window_start" field.
func DailyWindowStartIn(vs ...time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldDailyWindowStart, vs...))
}

// DailyWindowStartNotIn applies the NotIn predicate on the "daily_window_start" field.
func DailyWindowStartNotIn(vs ...time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldDailyWindowStart, vs...))
}

// DailyWindowStartGT applies the GT predicate on the "daily_window_start" field.
func DailyWindowStartGT(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldDailyWindowStart, v))
}

// DailyWindowStartGTE applies the GTE predicate on the "daily_window_start" field.
func DailyWindowStartGTE(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldDailyWindowStart, v))
}

// DailyWindowStartLT applies the LT predicate on the "daily_window_start" field.
func DailyWindowStartLT(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldDailyWindowStart, v))
}

// DailyWindowStartLTE applies the LTE predicate on the "daily_window_start" field.
func DailyWindowStartLTE(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldDailyWindowStart, v))
}

// DailyWindowStartIsNil applies the IsNil predicate on the "daily_window_start" field.
func DailyWindowStartIsNil() predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIsNull(FieldDailyWindowStart))
}

// DailyWindowStartNotNil applies the NotNil predicate on the "daily_window_start" field.
func DailyWindowStartNotNil() predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotNull(FieldDailyWindowStart))
}

// WeeklyWindowStartEQ applies the EQ predicate on the "weekly_window_start" field.
func WeeklyWindowStartEQ(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartNEQ applies the NEQ predicate on the "weekly_window_start" field.
func WeeklyWindowStartNEQ(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartIn applies the In predicate on the "weekly_window_start" field.
func WeeklyWindowStartIn(vs ...time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldWeeklyWindowStart, vs...))
}

// WeeklyWindowStartNotIn applies the NotIn predicate on the "weekly_window_start" field.
func WeeklyWindowStartNotIn(vs ...time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldWeeklyWindowStart, vs...))
}

// WeeklyWindowStartGT applies the GT predicate on the "weekly_window_start" field.
func WeeklyWindowStartGT(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartGTE applies the GTE predicate on the "weekly_window_start" field.
func WeeklyWindowStartGTE(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartLT applies the LT predicate on the "weekly_window_start" field.
func WeeklyWindowStartLT(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartLTE applies the LTE predicate on the "weekly_window_start" field.
func WeeklyWindowStartLTE(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartIsNil applies the IsNil predicate on the "weekly_window_start" field.
func WeeklyWindowStartIsNil() predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIsNull(FieldWeeklyWindowStart))
}

// WeeklyWindowStartNotNil applies the NotNil predicate on the "weekly_window_start" field.
func WeeklyWindowStartNotNil() predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotNull(FieldWeeklyWindowStart))
}

// MonthlyWindowStartEQ applies the EQ predicate on the "monthly_window_start" field.
func MonthlyWindowStartEQ(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartNEQ applies the NEQ predicate on the "monthly_window_start" field.
func MonthlyWindowStartNEQ(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartIn applies the In predicate on the "monthly_window_start" field.
func MonthlyWindowStartIn(vs ...time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldMonthlyWindowStart, vs...))
}

// MonthlyWindowStartNotIn applies the NotIn predicate on the "monthly_window_start" field.
func MonthlyWindowStartNotIn(vs ...time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldMonthlyWindowStart, vs...))
}

// MonthlyWindowStartGT applies the GT predicate on the "monthly_window_start" field.
func MonthlyWindowStartGT(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartGTE applies the GTE predicate on the "monthly_window_start" field.
func MonthlyWindowStartGTE(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartLT applies the LT predicate on the "monthly_window_start" field.
func MonthlyWindowStartLT(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartLTE applies the LTE predicate on the "monthly_window_start" field.
func MonthlyWindowStartLTE(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartIsNil applies the IsNil predicate on the "monthly_window_start" field.
func MonthlyWindowStartIsNil() predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIsNull(FieldMonthlyWindowStart))
}

// MonthlyWindowStartNotNil applies the NotNil predicate on the "monthly_window_start" field.
func MonthlyWindowStartNotNil() predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotNull(FieldMonthlyWindowStart))
}

// AsyncTaskIDEQ applies the EQ predicate on the "async_task_id" field.
func AsyncTaskIDEQ(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldAsyncTaskID, v))
}

// AsyncTaskIDNEQ applies the NEQ predicate on the "async_task_id" field.
func AsyncTaskIDNEQ(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldAsyncTaskID, v))
}

// AsyncTaskIDIn applies the In predicate on the "async_task_id" field.
func AsyncTaskIDIn(vs ...string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldAsyncTaskID, vs...))
}

// AsyncTaskIDNotIn applies the NotIn predicate on the "async_task_id" field.
func AsyncTaskIDNotIn(vs ...string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldAsyncTaskID, vs...))
}

// AsyncTaskIDGT applies the GT predicate on the "async_task_id" field.
func AsyncTaskIDGT(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldAsyncTaskID, v))
}

// AsyncTaskIDGTE applies the GTE predicate on the "async_task_id" field.
func AsyncTaskIDGTE(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldAsyncTaskID, v))
}

// AsyncTaskIDLT applies the LT predicate on the "async_task_id" field.
func AsyncTaskIDLT(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldAsyncTaskID, v))
}

// AsyncTaskIDLTE applies the LTE predicate on the "async_task_id" field.
func AsyncTaskIDLTE(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldAsyncTaskID, v))
}

// AsyncTaskIDContains applies the Contains predicate on the "async_task_id" field.
func AsyncTaskIDContains(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldContains(FieldAsyncTaskID, v))
}

// AsyncTaskIDHasPrefix applies the HasPrefix predicate on the "async_task_id" field.
func AsyncTaskIDHasPrefix(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldHasPrefix(FieldAsyncTaskID, v))
}

// AsyncTaskIDHasSuffix applies the HasSuffix predicate on the "async_task_id" field.
func AsyncTaskIDHasSuffix(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldHasSuffix(FieldAsyncTaskID, v))
}

// AsyncTaskIDIsNil applies the IsNil predicate on the "async_task_id" field.
func AsyncTaskIDIsNil() predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIsNull(FieldAsyncTaskID))
}

// AsyncTaskIDNotNil applies the NotNil predicate on the "async_task_id" field.
func AsyncTaskIDNotNil() predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotNull(FieldAsyncTaskID))
}

// AsyncTaskIDEqualFold applies the EqualFold predicate on the "async_task_id" field.
func AsyncTaskIDEqualFold(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEqualFold(FieldAsyncTaskID, v))
}

// AsyncTaskIDContainsFold applies the ContainsFold predicate on the "async_task_id" field.
func AsyncTaskIDContainsFold(v string) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldContainsFold(FieldAsyncTaskID, v))
}

// AsyncMetadataIsNil applies the IsNil predicate on the "async_metadata" field.
func AsyncMetadataIsNil() predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIsNull(FieldAsyncMetadata))
}

// AsyncMetadataNotNil applies the NotNil predicate on the "async_metadata" field.
func AsyncMetadataNotNil() predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotNull(FieldAsyncMetadata))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BillingReservation {
	return predicate.BillingReservation(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BillingReservation) predicate.BillingReservation {
	return predicate.BillingReservation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BillingReservation) predicate.BillingReservation {
	return predicate.BillingReservation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BillingReservation) predicate.BillingReservation {
	return predicate.BillingReservation(sql.NotPredicates(p))
}
